/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_networkRxDisplay_H_
#define _chains_networkRxDisplay_H_

#include <include/link_api/system.h>
#include <include/link_api/nullSrcLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    NullSourceLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_VideoLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       NullSrcLink_CreateParams                NullSourcePrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_VideoPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_networkRxDisplayObj;

Void chains_networkRxDisplay_SetLinkId(chains_networkRxDisplayObj *pObj);

Void chains_networkRxDisplay_ResetLinkPrms(chains_networkRxDisplayObj *pObj);

Void chains_networkRxDisplay_SetPrms(chains_networkRxDisplayObj *pObj);

Void chains_networkRxDisplay_ConnectLinks(chains_networkRxDisplayObj *pObj);

Int32 chains_networkRxDisplay_Create(chains_networkRxDisplayObj *pObj, Void *appObj);

Int32 chains_networkRxDisplay_Start(chains_networkRxDisplayObj *pObj);

Int32 chains_networkRxDisplay_Stop(chains_networkRxDisplayObj *pObj);

Int32 chains_networkRxDisplay_Delete(chains_networkRxDisplayObj *pObj);

Void chains_networkRxDisplay_printBufferStatistics(chains_networkRxDisplayObj *pObj);

Void chains_networkRxDisplay_printStatistics(chains_networkRxDisplayObj *pObj);

Void chains_networkRxDisplay_SetAppPrms(chains_networkRxDisplayObj *pObj, Void *appObj);

#endif /* _chains_networkRxDisplay_H_ */
