
SRCDIR += $(vision_sdk_PATH)/examples/tda2xx/src/usecases/network_rx_tx

SRCS_ipu1_0 += \
		chains_networkRxDisplay.c \
		chains_networkTxCapture.c \
		chains_networkTxMultiCamCapture.c \
		chains_networkTxEncCapture.c \
		chains_networkRxDecDisplay.c \
		chains_networkRxDisplay_priv.c \
		chains_networkTxCapture_priv.c \
		chains_networkTxEncCapture_priv.c \
		chains_networkTxMultiCamCapture_priv.c \
		chains_networkRxDecDisplay_priv.c \
		chains_networkRxTx.c

