/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_vipSingleCameraDenseOpticalFlow_4eve_priv.h"
Void chains_vipSingleCameraDenseOpticalFlow_4eve_SetLinkId(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE;
       pObj->Dup_captureLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->IPCOut_IPU1_0_EVE4_3LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_3);
       pObj->IPCIn_EVE4_IPU1_0_0LinkID      = EVE4_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_DenseOptFlow_4LinkID       = EVE4_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE4_DSP1_0LinkID       = EVE4_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP1_EVE4_3LinkID        = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_3);
       pObj->IPCOut_IPU1_0_EVE3_2LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_EVE3_IPU1_0_0LinkID      = EVE3_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_DenseOptFlow_3LinkID       = EVE3_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE3_DSP1_0LinkID       = EVE3_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP1_EVE3_2LinkID        = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->IPCOut_IPU1_0_EVE2_1LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_EVE2_IPU1_0_0LinkID      = EVE2_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_DenseOptFlow_2LinkID       = EVE2_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE2_DSP1_0LinkID       = EVE2_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP1_EVE2_1LinkID        = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->IPCOut_IPU1_0_EVE1_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_EVE1_IPU1_0_0LinkID      = EVE1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_DenseOptFlow_1LinkID       = EVE1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE1_DSP1_0LinkID       = EVE1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP1_EVE1_0LinkID        = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Merge_DofLinkID                = DSP1_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->Alg_VectorToImageLinkID        = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP1_IPU1_0_0LinkID     = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_DSP1_0LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Display_VideoDofLinkID         = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->VPE_captureLinkID              = SYSTEM_LINK_ID_VPE_0;
       pObj->Display_VideoOriginalLinkID    = SYSTEM_LINK_ID_DISPLAY_1;
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_2;
}

Void chains_vipSingleCameraDenseOpticalFlow_4eve_ResetLinkPrms(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       DupLink_CreateParams_Init(&pObj->Dup_capturePrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE4_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE4_IPU1_0_0Prm);
       AlgorithmLink_DenseOptFlowCreateParams_Init(&pObj->Alg_DenseOptFlow_4Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE4_DSP1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_EVE4_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE3_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE3_IPU1_0_0Prm);
       AlgorithmLink_DenseOptFlowCreateParams_Init(&pObj->Alg_DenseOptFlow_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE3_DSP1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_EVE3_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE2_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE2_IPU1_0_0Prm);
       AlgorithmLink_DenseOptFlowCreateParams_Init(&pObj->Alg_DenseOptFlow_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE2_DSP1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_EVE2_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE1_IPU1_0_0Prm);
       AlgorithmLink_DenseOptFlowCreateParams_Init(&pObj->Alg_DenseOptFlow_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE1_DSP1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_EVE1_0Prm);
       MergeLink_CreateParams_Init(&pObj->Merge_DofPrm);
       AlgorithmLink_VectorToImageCreateParams_Init(&pObj->Alg_VectorToImagePrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP1_0Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_VideoDofPrm);
       VpeLink_CreateParams_Init(&pObj->VPE_capturePrm);
       DisplayLink_CreateParams_Init(&pObj->Display_VideoOriginalPrm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
}

Void chains_vipSingleCameraDenseOpticalFlow_4eve_SetPrms(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){
       (pObj->Dup_capturePrm).numOutQue = 5;
       (pObj->Alg_DenseOptFlow_4Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DenseOptFlowCreateParams);
       (pObj->Alg_DenseOptFlow_4Prm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_DENSE_OPTICAL_FLOW;
       (pObj->Alg_DenseOptFlow_3Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DenseOptFlowCreateParams);
       (pObj->Alg_DenseOptFlow_3Prm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_DENSE_OPTICAL_FLOW;
       (pObj->Alg_DenseOptFlow_2Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DenseOptFlowCreateParams);
       (pObj->Alg_DenseOptFlow_2Prm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_DENSE_OPTICAL_FLOW;
       (pObj->Alg_DenseOptFlow_1Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DenseOptFlowCreateParams);
       (pObj->Alg_DenseOptFlow_1Prm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_DENSE_OPTICAL_FLOW;
       (pObj->Merge_DofPrm).numInQue = 4;
       (pObj->Alg_VectorToImagePrm).baseClassCreate.size  = sizeof(AlgorithmLink_VectorToImageCreateParams);
       (pObj->Alg_VectorToImagePrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_VECTORTOIMAGE;
}

Void chains_vipSingleCameraDenseOpticalFlow_4eve_ConnectLinks(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){

       //Capture -> Dup_capture
       pObj->CapturePrm.outQueParams.nextLink = pObj->Dup_captureLinkID;
       pObj->Dup_capturePrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->Dup_capturePrm.inQueParams.prevLinkQueId = 0;

       //Dup_capture -> IPCOut_IPU1_0_EVE1_0
       pObj->Dup_capturePrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkQueId = 0;

       //Dup_capture -> IPCOut_IPU1_0_EVE2_1
       pObj->Dup_capturePrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_EVE2_1LinkID;
       pObj->IPCOut_IPU1_0_EVE2_1Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_EVE2_1Prm.inQueParams.prevLinkQueId = 1;

       //Dup_capture -> IPCOut_IPU1_0_EVE3_2
       pObj->Dup_capturePrm.outQueParams[2].nextLink = pObj->IPCOut_IPU1_0_EVE3_2LinkID;
       pObj->IPCOut_IPU1_0_EVE3_2Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_EVE3_2Prm.inQueParams.prevLinkQueId = 2;

       //Dup_capture -> IPCOut_IPU1_0_EVE4_3
       pObj->Dup_capturePrm.outQueParams[3].nextLink = pObj->IPCOut_IPU1_0_EVE4_3LinkID;
       pObj->IPCOut_IPU1_0_EVE4_3Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_EVE4_3Prm.inQueParams.prevLinkQueId = 3;

       //Dup_capture -> VPE_capture
       pObj->Dup_capturePrm.outQueParams[4].nextLink = pObj->VPE_captureLinkID;
       pObj->VPE_capturePrm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->VPE_capturePrm.inQueParams.prevLinkQueId = 4;

       //IPCOut_IPU1_0_EVE4_3 -> IPCIn_EVE4_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE4_3Prm.outQueParams.nextLink = pObj->IPCIn_EVE4_IPU1_0_0LinkID;
       pObj->IPCIn_EVE4_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE4_3LinkID;
       pObj->IPCIn_EVE4_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE4_IPU1_0_0 -> Alg_DenseOptFlow_4
       pObj->IPCIn_EVE4_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_DenseOptFlow_4LinkID;
       pObj->Alg_DenseOptFlow_4Prm.inQueParams.prevLinkId = pObj->IPCIn_EVE4_IPU1_0_0LinkID;
       pObj->Alg_DenseOptFlow_4Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DenseOptFlow_4 -> IPCOut_EVE4_DSP1_0
       pObj->Alg_DenseOptFlow_4Prm.outQueParams.nextLink = pObj->IPCOut_EVE4_DSP1_0LinkID;
       pObj->IPCOut_EVE4_DSP1_0Prm.inQueParams.prevLinkId = pObj->Alg_DenseOptFlow_4LinkID;
       pObj->IPCOut_EVE4_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE4_DSP1_0 -> IPCIn_DSP1_EVE4_3
       pObj->IPCOut_EVE4_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_EVE4_3LinkID;
       pObj->IPCIn_DSP1_EVE4_3Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE4_DSP1_0LinkID;
       pObj->IPCIn_DSP1_EVE4_3Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_EVE4_3 -> Merge_Dof
       pObj->IPCIn_DSP1_EVE4_3Prm.outQueParams.nextLink = pObj->Merge_DofLinkID;
       pObj->Merge_DofPrm.inQueParams[3].prevLinkId = pObj->IPCIn_DSP1_EVE4_3LinkID;
       pObj->Merge_DofPrm.inQueParams[3].prevLinkQueId = 0;

       //IPCOut_IPU1_0_EVE3_2 -> IPCIn_EVE3_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE3_2Prm.outQueParams.nextLink = pObj->IPCIn_EVE3_IPU1_0_0LinkID;
       pObj->IPCIn_EVE3_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE3_2LinkID;
       pObj->IPCIn_EVE3_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE3_IPU1_0_0 -> Alg_DenseOptFlow_3
       pObj->IPCIn_EVE3_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_DenseOptFlow_3LinkID;
       pObj->Alg_DenseOptFlow_3Prm.inQueParams.prevLinkId = pObj->IPCIn_EVE3_IPU1_0_0LinkID;
       pObj->Alg_DenseOptFlow_3Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DenseOptFlow_3 -> IPCOut_EVE3_DSP1_0
       pObj->Alg_DenseOptFlow_3Prm.outQueParams.nextLink = pObj->IPCOut_EVE3_DSP1_0LinkID;
       pObj->IPCOut_EVE3_DSP1_0Prm.inQueParams.prevLinkId = pObj->Alg_DenseOptFlow_3LinkID;
       pObj->IPCOut_EVE3_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE3_DSP1_0 -> IPCIn_DSP1_EVE3_2
       pObj->IPCOut_EVE3_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_EVE3_2LinkID;
       pObj->IPCIn_DSP1_EVE3_2Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE3_DSP1_0LinkID;
       pObj->IPCIn_DSP1_EVE3_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_EVE3_2 -> Merge_Dof
       pObj->IPCIn_DSP1_EVE3_2Prm.outQueParams.nextLink = pObj->Merge_DofLinkID;
       pObj->Merge_DofPrm.inQueParams[2].prevLinkId = pObj->IPCIn_DSP1_EVE3_2LinkID;
       pObj->Merge_DofPrm.inQueParams[2].prevLinkQueId = 0;

       //IPCOut_IPU1_0_EVE2_1 -> IPCIn_EVE2_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE2_1Prm.outQueParams.nextLink = pObj->IPCIn_EVE2_IPU1_0_0LinkID;
       pObj->IPCIn_EVE2_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE2_1LinkID;
       pObj->IPCIn_EVE2_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE2_IPU1_0_0 -> Alg_DenseOptFlow_2
       pObj->IPCIn_EVE2_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_DenseOptFlow_2LinkID;
       pObj->Alg_DenseOptFlow_2Prm.inQueParams.prevLinkId = pObj->IPCIn_EVE2_IPU1_0_0LinkID;
       pObj->Alg_DenseOptFlow_2Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DenseOptFlow_2 -> IPCOut_EVE2_DSP1_0
       pObj->Alg_DenseOptFlow_2Prm.outQueParams.nextLink = pObj->IPCOut_EVE2_DSP1_0LinkID;
       pObj->IPCOut_EVE2_DSP1_0Prm.inQueParams.prevLinkId = pObj->Alg_DenseOptFlow_2LinkID;
       pObj->IPCOut_EVE2_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE2_DSP1_0 -> IPCIn_DSP1_EVE2_1
       pObj->IPCOut_EVE2_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_EVE2_1LinkID;
       pObj->IPCIn_DSP1_EVE2_1Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE2_DSP1_0LinkID;
       pObj->IPCIn_DSP1_EVE2_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_EVE2_1 -> Merge_Dof
       pObj->IPCIn_DSP1_EVE2_1Prm.outQueParams.nextLink = pObj->Merge_DofLinkID;
       pObj->Merge_DofPrm.inQueParams[1].prevLinkId = pObj->IPCIn_DSP1_EVE2_1LinkID;
       pObj->Merge_DofPrm.inQueParams[1].prevLinkQueId = 0;

       //IPCOut_IPU1_0_EVE1_0 -> IPCIn_EVE1_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE1_0Prm.outQueParams.nextLink = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE1_IPU1_0_0 -> Alg_DenseOptFlow_1
       pObj->IPCIn_EVE1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_DenseOptFlow_1LinkID;
       pObj->Alg_DenseOptFlow_1Prm.inQueParams.prevLinkId = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->Alg_DenseOptFlow_1Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DenseOptFlow_1 -> IPCOut_EVE1_DSP1_0
       pObj->Alg_DenseOptFlow_1Prm.outQueParams.nextLink = pObj->IPCOut_EVE1_DSP1_0LinkID;
       pObj->IPCOut_EVE1_DSP1_0Prm.inQueParams.prevLinkId = pObj->Alg_DenseOptFlow_1LinkID;
       pObj->IPCOut_EVE1_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE1_DSP1_0 -> IPCIn_DSP1_EVE1_0
       pObj->IPCOut_EVE1_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_EVE1_0LinkID;
       pObj->IPCIn_DSP1_EVE1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE1_DSP1_0LinkID;
       pObj->IPCIn_DSP1_EVE1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_EVE1_0 -> Merge_Dof
       pObj->IPCIn_DSP1_EVE1_0Prm.outQueParams.nextLink = pObj->Merge_DofLinkID;
       pObj->Merge_DofPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP1_EVE1_0LinkID;
       pObj->Merge_DofPrm.inQueParams[0].prevLinkQueId = 0;

       //Merge_Dof -> Alg_VectorToImage
       pObj->Merge_DofPrm.outQueParams.nextLink = pObj->Alg_VectorToImageLinkID;
       pObj->Alg_VectorToImagePrm.inQueParams.prevLinkId = pObj->Merge_DofLinkID;
       pObj->Alg_VectorToImagePrm.inQueParams.prevLinkQueId = 0;

       //Alg_VectorToImage -> IPCOut_DSP1_IPU1_0_0
       pObj->Alg_VectorToImagePrm.outQueParams.nextLink = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_VectorToImageLinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP1_IPU1_0_0 -> IPCIn_IPU1_0_DSP1_0
       pObj->IPCOut_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_DSP1_0 -> Display_VideoDof
       pObj->IPCIn_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->Display_VideoDofLinkID;
       pObj->Display_VideoDofPrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
       pObj->Display_VideoDofPrm.inQueParams.prevLinkQueId = 0;

       //VPE_capture -> Display_VideoOriginal
       pObj->VPE_capturePrm.outQueParams[0].nextLink = pObj->Display_VideoOriginalLinkID;
       pObj->Display_VideoOriginalPrm.inQueParams.prevLinkId = pObj->VPE_captureLinkID;
       pObj->Display_VideoOriginalPrm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_vipSingleCameraDenseOpticalFlow_4eve_Create(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj, Void *appObj){

       Int32 status;

       chains_vipSingleCameraDenseOpticalFlow_4eve_SetLinkId(pObj);
       chains_vipSingleCameraDenseOpticalFlow_4eve_ResetLinkPrms(pObj);

       chains_vipSingleCameraDenseOpticalFlow_4eve_SetPrms(pObj);
       chains_vipSingleCameraDenseOpticalFlow_4eve_SetAppPrms(pObj, appObj);

       chains_vipSingleCameraDenseOpticalFlow_4eve_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_captureLinkID, &pObj->Dup_capturePrm, sizeof(pObj->Dup_capturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE4_3LinkID, &pObj->IPCOut_IPU1_0_EVE4_3Prm, sizeof(pObj->IPCOut_IPU1_0_EVE4_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE4_IPU1_0_0LinkID, &pObj->IPCIn_EVE4_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE4_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DenseOptFlow_4LinkID, &pObj->Alg_DenseOptFlow_4Prm, sizeof(pObj->Alg_DenseOptFlow_4Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE4_DSP1_0LinkID, &pObj->IPCOut_EVE4_DSP1_0Prm, sizeof(pObj->IPCOut_EVE4_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_EVE4_3LinkID, &pObj->IPCIn_DSP1_EVE4_3Prm, sizeof(pObj->IPCIn_DSP1_EVE4_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE3_2LinkID, &pObj->IPCOut_IPU1_0_EVE3_2Prm, sizeof(pObj->IPCOut_IPU1_0_EVE3_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE3_IPU1_0_0LinkID, &pObj->IPCIn_EVE3_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE3_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DenseOptFlow_3LinkID, &pObj->Alg_DenseOptFlow_3Prm, sizeof(pObj->Alg_DenseOptFlow_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE3_DSP1_0LinkID, &pObj->IPCOut_EVE3_DSP1_0Prm, sizeof(pObj->IPCOut_EVE3_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_EVE3_2LinkID, &pObj->IPCIn_DSP1_EVE3_2Prm, sizeof(pObj->IPCIn_DSP1_EVE3_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE2_1LinkID, &pObj->IPCOut_IPU1_0_EVE2_1Prm, sizeof(pObj->IPCOut_IPU1_0_EVE2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE2_IPU1_0_0LinkID, &pObj->IPCIn_EVE2_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE2_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DenseOptFlow_2LinkID, &pObj->Alg_DenseOptFlow_2Prm, sizeof(pObj->Alg_DenseOptFlow_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE2_DSP1_0LinkID, &pObj->IPCOut_EVE2_DSP1_0Prm, sizeof(pObj->IPCOut_EVE2_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_EVE2_1LinkID, &pObj->IPCIn_DSP1_EVE2_1Prm, sizeof(pObj->IPCIn_DSP1_EVE2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE1_0LinkID, &pObj->IPCOut_IPU1_0_EVE1_0Prm, sizeof(pObj->IPCOut_IPU1_0_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE1_IPU1_0_0LinkID, &pObj->IPCIn_EVE1_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DenseOptFlow_1LinkID, &pObj->Alg_DenseOptFlow_1Prm, sizeof(pObj->Alg_DenseOptFlow_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE1_DSP1_0LinkID, &pObj->IPCOut_EVE1_DSP1_0Prm, sizeof(pObj->IPCOut_EVE1_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_EVE1_0LinkID, &pObj->IPCIn_DSP1_EVE1_0Prm, sizeof(pObj->IPCIn_DSP1_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_DofLinkID, &pObj->Merge_DofPrm, sizeof(pObj->Merge_DofPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_VectorToImageLinkID, &pObj->Alg_VectorToImagePrm, sizeof(pObj->Alg_VectorToImagePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_IPU1_0_0LinkID, &pObj->IPCOut_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCOut_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP1_0LinkID, &pObj->IPCIn_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCIn_IPU1_0_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_VideoDofLinkID, &pObj->Display_VideoDofPrm, sizeof(pObj->Display_VideoDofPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_captureLinkID, &pObj->VPE_capturePrm, sizeof(pObj->VPE_capturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_VideoOriginalLinkID, &pObj->Display_VideoOriginalPrm, sizeof(pObj->Display_VideoOriginalPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCameraDenseOpticalFlow_4eve_Start(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_VideoOriginalLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_VideoDofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_VectorToImageLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_DofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE1_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DenseOptFlow_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_EVE2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE2_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DenseOptFlow_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_EVE3_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE3_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DenseOptFlow_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE3_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE3_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_EVE4_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE4_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DenseOptFlow_4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE4_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE4_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCameraDenseOpticalFlow_4eve_Stop(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_VideoOriginalLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_VideoDofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_VectorToImageLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_DofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE1_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DenseOptFlow_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_EVE2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE2_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DenseOptFlow_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_EVE3_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE3_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DenseOptFlow_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE3_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE3_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_EVE4_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE4_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DenseOptFlow_4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE4_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE4_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCameraDenseOpticalFlow_4eve_Delete(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_VideoOriginalLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_VideoDofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_VectorToImageLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_DofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE1_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DenseOptFlow_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_EVE2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE2_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DenseOptFlow_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_EVE3_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE3_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DenseOptFlow_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE3_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE3_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_EVE4_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE4_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DenseOptFlow_4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE4_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE4_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_vipSingleCameraDenseOpticalFlow_4eve_printBufferStatistics(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_captureLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE4_3LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE4_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DenseOptFlow_4LinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE4_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_EVE4_3LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE3_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE3_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DenseOptFlow_3LinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE3_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_EVE3_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE2_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DenseOptFlow_2LinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE2_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_EVE2_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DenseOptFlow_1LinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE1_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_EVE1_0LinkID);
       System_linkPrintBufferStatistics(pObj->Merge_DofLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_VectorToImageLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       System_linkPrintBufferStatistics(pObj->Display_VideoDofLinkID);
       System_linkPrintBufferStatistics(pObj->VPE_captureLinkID);
       System_linkPrintBufferStatistics(pObj->Display_VideoOriginalLinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_vipSingleCameraDenseOpticalFlow_4eve_printStatistics(chains_vipSingleCameraDenseOpticalFlow_4eveObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->Dup_captureLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE4_3LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE4_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_DenseOptFlow_4LinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE4_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_EVE4_3LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE3_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE3_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_DenseOptFlow_3LinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE3_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_EVE3_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE2_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_DenseOptFlow_2LinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE2_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_EVE2_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_DenseOptFlow_1LinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE1_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_EVE1_0LinkID);
       System_linkPrintStatistics(pObj->Merge_DofLinkID);
       System_linkPrintStatistics(pObj->Alg_VectorToImageLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       System_linkPrintStatistics(pObj->Display_VideoDofLinkID);
       System_linkPrintStatistics(pObj->VPE_captureLinkID);
       System_linkPrintStatistics(pObj->Display_VideoOriginalLinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

