/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_vipSingleCam_DualDisplayEdgeDetection_priv.h"
Void chains_vipSingleCam_DualDisplayEdgeDetection_SetLinkId(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE;
       pObj->Dup_CaptureLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->IPCOut_IPU1_0_EVE1_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_EVE1_IPU1_0_0LinkID      = EVE1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_EdgeDetectLinkID           = EVE1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE1_IPU1_0_0LinkID     = EVE1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_EVE1_0LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Display_LCDLinkID              = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->VPELinkID                      = SYSTEM_LINK_ID_VPE_0;
       pObj->Display_PIPLinkID              = SYSTEM_LINK_ID_DISPLAY_1;
       pObj->Display_HDMILinkID             = SYSTEM_LINK_ID_DISPLAY_2;
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_3;
}

Void chains_vipSingleCam_DualDisplayEdgeDetection_ResetLinkPrms(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       DupLink_CreateParams_Init(&pObj->Dup_CapturePrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_EVE1_0Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_LCDPrm);
       VpeLink_CreateParams_Init(&pObj->VPEPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_PIPPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_HDMIPrm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
}

Void chains_vipSingleCam_DualDisplayEdgeDetection_SetPrms(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){
       (pObj->Dup_CapturePrm).numOutQue = 3;
       (pObj->Alg_EdgeDetectPrm).baseClassCreate.size  = sizeof(AlgorithmLink_EdgeDetectionCreateParams);
       (pObj->Alg_EdgeDetectPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_EDGEDETECTION;
}

Void chains_vipSingleCam_DualDisplayEdgeDetection_ConnectLinks(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){

       //Capture -> Dup_Capture
       pObj->CapturePrm.outQueParams.nextLink = pObj->Dup_CaptureLinkID;
       pObj->Dup_CapturePrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->Dup_CapturePrm.inQueParams.prevLinkQueId = 0;

       //Dup_Capture -> Display_HDMI
       pObj->Dup_CapturePrm.outQueParams[0].nextLink = pObj->Display_HDMILinkID;
       pObj->Display_HDMIPrm.inQueParams.prevLinkId = pObj->Dup_CaptureLinkID;
       pObj->Display_HDMIPrm.inQueParams.prevLinkQueId = 0;

       //Dup_Capture -> IPCOut_IPU1_0_EVE1_0
       pObj->Dup_CapturePrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkId = pObj->Dup_CaptureLinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkQueId = 1;

       //Dup_Capture -> VPE
       pObj->Dup_CapturePrm.outQueParams[2].nextLink = pObj->VPELinkID;
       pObj->VPEPrm.inQueParams.prevLinkId = pObj->Dup_CaptureLinkID;
       pObj->VPEPrm.inQueParams.prevLinkQueId = 2;

       //IPCOut_IPU1_0_EVE1_0 -> IPCIn_EVE1_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE1_0Prm.outQueParams.nextLink = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE1_IPU1_0_0 -> Alg_EdgeDetect
       pObj->IPCIn_EVE1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_EdgeDetectLinkID;
       pObj->Alg_EdgeDetectPrm.inQueParams.prevLinkId = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->Alg_EdgeDetectPrm.inQueParams.prevLinkQueId = 0;

       //Alg_EdgeDetect -> IPCOut_EVE1_IPU1_0_0
       pObj->Alg_EdgeDetectPrm.outQueParams.nextLink = pObj->IPCOut_EVE1_IPU1_0_0LinkID;
       pObj->IPCOut_EVE1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_EdgeDetectLinkID;
       pObj->IPCOut_EVE1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE1_IPU1_0_0 -> IPCIn_IPU1_0_EVE1_0
       pObj->IPCOut_EVE1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_EVE1_0LinkID;
       pObj->IPCIn_IPU1_0_EVE1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE1_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_EVE1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_EVE1_0 -> Display_LCD
       pObj->IPCIn_IPU1_0_EVE1_0Prm.outQueParams.nextLink = pObj->Display_LCDLinkID;
       pObj->Display_LCDPrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_EVE1_0LinkID;
       pObj->Display_LCDPrm.inQueParams.prevLinkQueId = 0;

       //VPE -> Display_PIP
       pObj->VPEPrm.outQueParams[0].nextLink = pObj->Display_PIPLinkID;
       pObj->Display_PIPPrm.inQueParams.prevLinkId = pObj->VPELinkID;
       pObj->Display_PIPPrm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_vipSingleCam_DualDisplayEdgeDetection_Create(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj, Void *appObj){

       Int32 status;

       chains_vipSingleCam_DualDisplayEdgeDetection_SetLinkId(pObj);
       chains_vipSingleCam_DualDisplayEdgeDetection_ResetLinkPrms(pObj);

       chains_vipSingleCam_DualDisplayEdgeDetection_SetPrms(pObj);
       chains_vipSingleCam_DualDisplayEdgeDetection_SetAppPrms(pObj, appObj);

       chains_vipSingleCam_DualDisplayEdgeDetection_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_CaptureLinkID, &pObj->Dup_CapturePrm, sizeof(pObj->Dup_CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE1_0LinkID, &pObj->IPCOut_IPU1_0_EVE1_0Prm, sizeof(pObj->IPCOut_IPU1_0_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE1_IPU1_0_0LinkID, &pObj->IPCIn_EVE1_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_EdgeDetectLinkID, &pObj->Alg_EdgeDetectPrm, sizeof(pObj->Alg_EdgeDetectPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE1_IPU1_0_0LinkID, &pObj->IPCOut_EVE1_IPU1_0_0Prm, sizeof(pObj->IPCOut_EVE1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_EVE1_0LinkID, &pObj->IPCIn_IPU1_0_EVE1_0Prm, sizeof(pObj->IPCIn_IPU1_0_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_LCDLinkID, &pObj->Display_LCDPrm, sizeof(pObj->Display_LCDPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPELinkID, &pObj->VPEPrm, sizeof(pObj->VPEPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_PIPLinkID, &pObj->Display_PIPPrm, sizeof(pObj->Display_PIPPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_HDMILinkID, &pObj->Display_HDMIPrm, sizeof(pObj->Display_HDMIPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCam_DualDisplayEdgeDetection_Start(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_HDMILinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_PIPLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_LCDLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_EdgeDetectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCam_DualDisplayEdgeDetection_Stop(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_HDMILinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_PIPLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_LCDLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_EdgeDetectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCam_DualDisplayEdgeDetection_Delete(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_HDMILinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_PIPLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_LCDLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_EdgeDetectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_vipSingleCam_DualDisplayEdgeDetection_printBufferStatistics(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_EdgeDetectLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       System_linkPrintBufferStatistics(pObj->Display_LCDLinkID);
       System_linkPrintBufferStatistics(pObj->VPELinkID);
       System_linkPrintBufferStatistics(pObj->Display_PIPLinkID);
       System_linkPrintBufferStatistics(pObj->Display_HDMILinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_vipSingleCam_DualDisplayEdgeDetection_printStatistics(chains_vipSingleCam_DualDisplayEdgeDetectionObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->Dup_CaptureLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_EdgeDetectLinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_EVE1_0LinkID);
       System_linkPrintStatistics(pObj->Display_LCDLinkID);
       System_linkPrintStatistics(pObj->VPELinkID);
       System_linkPrintStatistics(pObj->Display_PIPLinkID);
       System_linkPrintStatistics(pObj->Display_HDMILinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

