/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_lvdsVipMultiCam_Sgx3Dsrv_H_
#define _chains_lvdsVipMultiCam_Sgx3Dsrv_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/algorithmLink_geometricAlignment.h>
#include <include/link_api/algorithmLink_synthesis.h>
#include <include/link_api/algorithmLink_photoAlignment.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/sgx3DsrvLink.h>
#include <include/link_api/nullLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    SyncLinkID;
       UInt32    Dup_svLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_2LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_3LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_4LinkID;
       UInt32    IPCOut_IPU1_0_DSP1_1LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_1LinkID;
       UInt32    IPCOut_IPU1_0_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Alg_GeoAlignLinkID;
       UInt32    IPCOut_DSP1_A15_0_1LinkID;
       UInt32    IPCIn_A15_0_DSP1_2LinkID;
       UInt32    Alg_SynthesisLinkID;
       UInt32    IPCOut_DSP1_A15_0_2LinkID;
       UInt32    IPCIn_A15_0_DSP1_3LinkID;
       UInt32    Alg_PhotoAlignLinkID;
       UInt32    IPCOut_DSP1_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_DSP1_1LinkID;
       UInt32    Sgx3DsrvLinkID;
       UInt32    NullLinkID;

       CaptureLink_CreateParams                CapturePrm;
       SyncLink_CreateParams                   SyncPrm;
       DupLink_CreateParams                    Dup_svPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_2Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_3Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_4Prm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_1Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_1Prm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       AlgorithmLink_GAlignCreateParams        Alg_GeoAlignPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_A15_0_1Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_DSP1_2Prm;
       AlgorithmLink_SynthesisCreateParams     Alg_SynthesisPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_A15_0_2Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_DSP1_3Prm;
       AlgorithmLink_PAlignCreateParams        Alg_PhotoAlignPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_DSP1_1Prm;
       Sgx3DsrvLink_CreateParams               Sgx3DsrvPrm;
       NullLink_CreateParams                   NullPrm;
} chains_lvdsVipMultiCam_Sgx3DsrvObj;

Void chains_lvdsVipMultiCam_Sgx3Dsrv_SetLinkId(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Void chains_lvdsVipMultiCam_Sgx3Dsrv_ResetLinkPrms(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Void chains_lvdsVipMultiCam_Sgx3Dsrv_SetPrms(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Void chains_lvdsVipMultiCam_Sgx3Dsrv_ConnectLinks(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Create(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj, Void *appObj);

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Start(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Stop(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Delete(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Void chains_lvdsVipMultiCam_Sgx3Dsrv_printBufferStatistics(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Void chains_lvdsVipMultiCam_Sgx3Dsrv_printStatistics(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj);

Void chains_lvdsVipMultiCam_Sgx3Dsrv_SetAppPrms(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj, Void *appObj);

#endif /* _chains_lvdsVipMultiCam_Sgx3Dsrv_H_ */
