/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipStereoCalibration_H_
#define _chains_vipStereoCalibration_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_softIsp.h>
#include <include/link_api/algorithmLink_remapMerge.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/vpeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_dmaSwMs.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_EVE1_0LinkID;
       UInt32    IPCIn_EVE1_IPU1_0_0LinkID;
       UInt32    Alg_SoftIspLinkID;
       UInt32    IPCOut_EVE1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_EVE1_0LinkID;
       UInt32    VPE_softispLinkID;
       UInt32    IPCOut_IPU1_0_EVE2_1LinkID;
       UInt32    IPCIn_EVE2_IPU1_0_0LinkID;
       UInt32    Alg_RemapMergeLinkID;
       UInt32    IPCOut_EVE2_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_EVE2_1LinkID;
       UInt32    VPE_orgdispLinkID;
       UInt32    Sync_orgLinkID;
       UInt32    Alg_DmaSwMsLinkID;
       UInt32    Display_orgLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_EVE1_0Prm;
       IpcLink_CreateParams                    IPCIn_EVE1_IPU1_0_0Prm;
       AlgorithmLink_SoftIspCreateParams       Alg_SoftIspPrm;
       IpcLink_CreateParams                    IPCOut_EVE1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_EVE1_0Prm;
       VpeLink_CreateParams                    VPE_softispPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_EVE2_1Prm;
       IpcLink_CreateParams                    IPCIn_EVE2_IPU1_0_0Prm;
       AlgorithmLink_RemapMergeCreateParams    Alg_RemapMergePrm;
       IpcLink_CreateParams                    IPCOut_EVE2_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_EVE2_1Prm;
       VpeLink_CreateParams                    VPE_orgdispPrm;
       SyncLink_CreateParams                   Sync_orgPrm;
       AlgorithmLink_DmaSwMsCreateParams       Alg_DmaSwMsPrm;
       DisplayLink_CreateParams                Display_orgPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipStereoCalibrationObj;

Void chains_vipStereoCalibration_SetLinkId(chains_vipStereoCalibrationObj *pObj);

Void chains_vipStereoCalibration_ResetLinkPrms(chains_vipStereoCalibrationObj *pObj);

Void chains_vipStereoCalibration_SetPrms(chains_vipStereoCalibrationObj *pObj);

Void chains_vipStereoCalibration_ConnectLinks(chains_vipStereoCalibrationObj *pObj);

Int32 chains_vipStereoCalibration_Create(chains_vipStereoCalibrationObj *pObj, Void *appObj);

Int32 chains_vipStereoCalibration_Start(chains_vipStereoCalibrationObj *pObj);

Int32 chains_vipStereoCalibration_Stop(chains_vipStereoCalibrationObj *pObj);

Int32 chains_vipStereoCalibration_Delete(chains_vipStereoCalibrationObj *pObj);

Void chains_vipStereoCalibration_printBufferStatistics(chains_vipStereoCalibrationObj *pObj);

Void chains_vipStereoCalibration_printStatistics(chains_vipStereoCalibrationObj *pObj);

Void chains_vipStereoCalibration_SetAppPrms(chains_vipStereoCalibrationObj *pObj, Void *appObj);

#endif /* _chains_vipStereoCalibration_H_ */
