/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraLaneDetect_H_
#define _chains_vipSingleCameraLaneDetect_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/algorithmLink_laneDetect.h>
#include <include/link_api/mergeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_laneDetectDraw.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Dup_captureLinkID;
       UInt32    Alg_LaneDetectLinkID;
       UInt32    Merge_algLinkID;
       UInt32    Sync_algLinkID;
       UInt32    Alg_LaneDetectDrawLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_0LinkID;
       UInt32    Display_algLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       DupLink_CreateParams                    Dup_capturePrm;
       AlgorithmLink_LaneDetectCreateParams    Alg_LaneDetectPrm;
       MergeLink_CreateParams                  Merge_algPrm;
       SyncLink_CreateParams                   Sync_algPrm;
       AlgorithmLink_LaneDetectDrawCreateParams Alg_LaneDetectDrawPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_0Prm;
       DisplayLink_CreateParams                Display_algPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraLaneDetectObj;

Void chains_vipSingleCameraLaneDetect_SetLinkId(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_ResetLinkPrms(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_SetPrms(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_ConnectLinks(chains_vipSingleCameraLaneDetectObj *pObj);

Int32 chains_vipSingleCameraLaneDetect_Create(chains_vipSingleCameraLaneDetectObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraLaneDetect_Start(chains_vipSingleCameraLaneDetectObj *pObj);

Int32 chains_vipSingleCameraLaneDetect_Stop(chains_vipSingleCameraLaneDetectObj *pObj);

Int32 chains_vipSingleCameraLaneDetect_Delete(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_printBufferStatistics(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_printStatistics(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_SetAppPrms(chains_vipSingleCameraLaneDetectObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraLaneDetect_H_ */
