/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_networkStereoDisplay_priv.h"
Void chains_networkStereoDisplay_SetLinkId(chains_networkStereoDisplayObj *pObj){
       pObj->NullSourceLinkID               = A15_0_LINK (SYSTEM_LINK_ID_NULL_SRC_0);
       pObj->IPCOut_A15_0_IPU1_0_0LinkID    = A15_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_A15_0_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->DecodeLinkID                   = SYSTEM_LINK_ID_VDEC_0;
       pObj->VPE_decodeOutLinkID            = SYSTEM_LINK_ID_VPE_0;
       pObj->Dup_origLinkID                 = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->Sync_dispLinkID                = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_1);
       pObj->Dup_CensusInputLinkID          = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_1);
       pObj->IPCOut_IPU1_0_EVE2_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_EVE2_IPU1_0_0LinkID      = EVE2_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_CensusLinkID               = EVE2_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE2_EVE3_0LinkID       = EVE2_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_EVE3_EVE2_0LinkID        = EVE3_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_DisparityHamDistLinkID     = EVE3_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE3_IPU1_0_0LinkID     = EVE3_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_EVE3_1LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->MergeLinkID                    = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->IPCOut_IPU1_0_DSP1_1LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_DSP1_IPU1_0_0LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_StereoPostProcessLinkID    = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP1_IPU1_0_0LinkID     = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_DSP1_2LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->VPE_disparityLinkID            = SYSTEM_LINK_ID_VPE_1;
       pObj->Display_disparityLinkID        = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->VPE_orgdispLinkID              = SYSTEM_LINK_ID_VPE_2;
       pObj->Sync_orgLinkID                 = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_DmaSwMsLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->Display_orgLinkID              = SYSTEM_LINK_ID_DISPLAY_1;
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_2;
}

Void chains_networkStereoDisplay_ResetLinkPrms(chains_networkStereoDisplayObj *pObj){
       NullSrcLink_CreateParams_Init(&pObj->NullSourcePrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_A15_0_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_A15_0_0Prm);
       DecLink_CreateParams_Init(&pObj->DecodePrm);
       VpeLink_CreateParams_Init(&pObj->VPE_decodeOutPrm);
       DupLink_CreateParams_Init(&pObj->Dup_origPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_dispPrm);
       DupLink_CreateParams_Init(&pObj->Dup_CensusInputPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE2_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE2_IPU1_0_0Prm);
       AlgorithmLink_Census_Init(&pObj->Alg_CensusPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE2_EVE3_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE3_EVE2_0Prm);
       AlgorithmLink_DisparityHamDist_Init(&pObj->Alg_DisparityHamDistPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE3_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_EVE3_1Prm);
       MergeLink_CreateParams_Init(&pObj->MergePrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP1_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_IPU1_0_0Prm);
       AlgorithmLink_StereoPostProcess_Init(&pObj->Alg_StereoPostProcessPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP1_2Prm);
       VpeLink_CreateParams_Init(&pObj->VPE_disparityPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_disparityPrm);
       VpeLink_CreateParams_Init(&pObj->VPE_orgdispPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_orgPrm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMsPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_orgPrm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
}

Void chains_networkStereoDisplay_SetPrms(chains_networkStereoDisplayObj *pObj){
       (pObj->Dup_origPrm).numOutQue = 2;
       (pObj->Dup_CensusInputPrm).numOutQue = 2;
       (pObj->Alg_CensusPrm).baseClassCreate.size  = sizeof(AlgorithmLink_CensusCreateParams);
       (pObj->Alg_CensusPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_CENSUS;
       (pObj->Alg_DisparityHamDistPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DisparityHamDistCreateParams);
       (pObj->Alg_DisparityHamDistPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_DISPARITY_HAMDIST;
       (pObj->MergePrm).numInQue = 2;
       (pObj->Alg_StereoPostProcessPrm).baseClassCreate.size  = sizeof(AlgorithmLink_StereoPostProcessCreateParams);
       (pObj->Alg_StereoPostProcessPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_STEREO_POST_PROCESS;
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
}

Void chains_networkStereoDisplay_ConnectLinks(chains_networkStereoDisplayObj *pObj){

       //NullSource -> IPCOut_A15_0_IPU1_0_0
       pObj->NullSourcePrm.outQueParams.nextLink = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->NullSourceLinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_A15_0_IPU1_0_0 -> IPCIn_IPU1_0_A15_0_0
       pObj->IPCOut_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_A15_0_0LinkID;
       pObj->IPCIn_IPU1_0_A15_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_A15_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_A15_0_0 -> Decode
       pObj->IPCIn_IPU1_0_A15_0_0Prm.outQueParams.nextLink = pObj->DecodeLinkID;
       pObj->DecodePrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_A15_0_0LinkID;
       pObj->DecodePrm.inQueParams.prevLinkQueId = 0;

       //Decode -> VPE_decodeOut
       pObj->DecodePrm.outQueParams.nextLink = pObj->VPE_decodeOutLinkID;
       pObj->VPE_decodeOutPrm.inQueParams.prevLinkId = pObj->DecodeLinkID;
       pObj->VPE_decodeOutPrm.inQueParams.prevLinkQueId = 0;

       //VPE_decodeOut -> Dup_orig
       pObj->VPE_decodeOutPrm.outQueParams[0].nextLink = pObj->Dup_origLinkID;
       pObj->Dup_origPrm.inQueParams.prevLinkId = pObj->VPE_decodeOutLinkID;
       pObj->Dup_origPrm.inQueParams.prevLinkQueId = 0;

       //Dup_orig -> VPE_orgdisp
       pObj->Dup_origPrm.outQueParams[0].nextLink = pObj->VPE_orgdispLinkID;
       pObj->VPE_orgdispPrm.inQueParams.prevLinkId = pObj->Dup_origLinkID;
       pObj->VPE_orgdispPrm.inQueParams.prevLinkQueId = 0;

       //Dup_orig -> Sync_disp
       pObj->Dup_origPrm.outQueParams[1].nextLink = pObj->Sync_dispLinkID;
       pObj->Sync_dispPrm.inQueParams.prevLinkId = pObj->Dup_origLinkID;
       pObj->Sync_dispPrm.inQueParams.prevLinkQueId = 1;

       //Sync_disp -> Dup_CensusInput
       pObj->Sync_dispPrm.outQueParams.nextLink = pObj->Dup_CensusInputLinkID;
       pObj->Dup_CensusInputPrm.inQueParams.prevLinkId = pObj->Sync_dispLinkID;
       pObj->Dup_CensusInputPrm.inQueParams.prevLinkQueId = 0;

       //Dup_CensusInput -> IPCOut_IPU1_0_EVE2_0
       pObj->Dup_CensusInputPrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_EVE2_0LinkID;
       pObj->IPCOut_IPU1_0_EVE2_0Prm.inQueParams.prevLinkId = pObj->Dup_CensusInputLinkID;
       pObj->IPCOut_IPU1_0_EVE2_0Prm.inQueParams.prevLinkQueId = 0;

       //Dup_CensusInput -> Merge
       pObj->Dup_CensusInputPrm.outQueParams[1].nextLink = pObj->MergeLinkID;
       pObj->MergePrm.inQueParams[1].prevLinkId = pObj->Dup_CensusInputLinkID;
       pObj->MergePrm.inQueParams[1].prevLinkQueId = 1;

       //IPCOut_IPU1_0_EVE2_0 -> IPCIn_EVE2_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE2_0Prm.outQueParams.nextLink = pObj->IPCIn_EVE2_IPU1_0_0LinkID;
       pObj->IPCIn_EVE2_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE2_0LinkID;
       pObj->IPCIn_EVE2_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE2_IPU1_0_0 -> Alg_Census
       pObj->IPCIn_EVE2_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_CensusLinkID;
       pObj->Alg_CensusPrm.inQueParams.prevLinkId = pObj->IPCIn_EVE2_IPU1_0_0LinkID;
       pObj->Alg_CensusPrm.inQueParams.prevLinkQueId = 0;

       //Alg_Census -> IPCOut_EVE2_EVE3_0
       pObj->Alg_CensusPrm.outQueParams.nextLink = pObj->IPCOut_EVE2_EVE3_0LinkID;
       pObj->IPCOut_EVE2_EVE3_0Prm.inQueParams.prevLinkId = pObj->Alg_CensusLinkID;
       pObj->IPCOut_EVE2_EVE3_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE2_EVE3_0 -> IPCIn_EVE3_EVE2_0
       pObj->IPCOut_EVE2_EVE3_0Prm.outQueParams.nextLink = pObj->IPCIn_EVE3_EVE2_0LinkID;
       pObj->IPCIn_EVE3_EVE2_0Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE2_EVE3_0LinkID;
       pObj->IPCIn_EVE3_EVE2_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE3_EVE2_0 -> Alg_DisparityHamDist
       pObj->IPCIn_EVE3_EVE2_0Prm.outQueParams.nextLink = pObj->Alg_DisparityHamDistLinkID;
       pObj->Alg_DisparityHamDistPrm.inQueParams.prevLinkId = pObj->IPCIn_EVE3_EVE2_0LinkID;
       pObj->Alg_DisparityHamDistPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DisparityHamDist -> IPCOut_EVE3_IPU1_0_0
       pObj->Alg_DisparityHamDistPrm.outQueParams.nextLink = pObj->IPCOut_EVE3_IPU1_0_0LinkID;
       pObj->IPCOut_EVE3_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_DisparityHamDistLinkID;
       pObj->IPCOut_EVE3_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE3_IPU1_0_0 -> IPCIn_IPU1_0_EVE3_1
       pObj->IPCOut_EVE3_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_EVE3_1LinkID;
       pObj->IPCIn_IPU1_0_EVE3_1Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE3_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_EVE3_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_EVE3_1 -> Merge
       pObj->IPCIn_IPU1_0_EVE3_1Prm.outQueParams.nextLink = pObj->MergeLinkID;
       pObj->MergePrm.inQueParams[0].prevLinkId = pObj->IPCIn_IPU1_0_EVE3_1LinkID;
       pObj->MergePrm.inQueParams[0].prevLinkQueId = 0;

       //Merge -> IPCOut_IPU1_0_DSP1_1
       pObj->MergePrm.outQueParams.nextLink = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkId = pObj->MergeLinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP1_1 -> IPCIn_DSP1_IPU1_0_0
       pObj->IPCOut_IPU1_0_DSP1_1Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_IPU1_0_0 -> Alg_StereoPostProcess
       pObj->IPCIn_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_StereoPostProcessLinkID;
       pObj->Alg_StereoPostProcessPrm.inQueParams.prevLinkId = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->Alg_StereoPostProcessPrm.inQueParams.prevLinkQueId = 0;

       //Alg_StereoPostProcess -> IPCOut_DSP1_IPU1_0_0
       pObj->Alg_StereoPostProcessPrm.outQueParams.nextLink = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_StereoPostProcessLinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP1_IPU1_0_0 -> IPCIn_IPU1_0_DSP1_2
       pObj->IPCOut_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP1_2LinkID;
       pObj->IPCIn_IPU1_0_DSP1_2Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_DSP1_2 -> VPE_disparity
       pObj->IPCIn_IPU1_0_DSP1_2Prm.outQueParams.nextLink = pObj->VPE_disparityLinkID;
       pObj->VPE_disparityPrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_DSP1_2LinkID;
       pObj->VPE_disparityPrm.inQueParams.prevLinkQueId = 0;

       //VPE_disparity -> Display_disparity
       pObj->VPE_disparityPrm.outQueParams[0].nextLink = pObj->Display_disparityLinkID;
       pObj->Display_disparityPrm.inQueParams.prevLinkId = pObj->VPE_disparityLinkID;
       pObj->Display_disparityPrm.inQueParams.prevLinkQueId = 0;

       //VPE_orgdisp -> Sync_org
       pObj->VPE_orgdispPrm.outQueParams[0].nextLink = pObj->Sync_orgLinkID;
       pObj->Sync_orgPrm.inQueParams.prevLinkId = pObj->VPE_orgdispLinkID;
       pObj->Sync_orgPrm.inQueParams.prevLinkQueId = 0;

       //Sync_org -> Alg_DmaSwMs
       pObj->Sync_orgPrm.outQueParams.nextLink = pObj->Alg_DmaSwMsLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkId = pObj->Sync_orgLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs -> Display_org
       pObj->Alg_DmaSwMsPrm.outQueParams.nextLink = pObj->Display_orgLinkID;
       pObj->Display_orgPrm.inQueParams.prevLinkId = pObj->Alg_DmaSwMsLinkID;
       pObj->Display_orgPrm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_networkStereoDisplay_Create(chains_networkStereoDisplayObj *pObj, Void *appObj){

       Int32 status;

       chains_networkStereoDisplay_SetLinkId(pObj);
       chains_networkStereoDisplay_ResetLinkPrms(pObj);

       chains_networkStereoDisplay_SetPrms(pObj);
       chains_networkStereoDisplay_SetAppPrms(pObj, appObj);

       chains_networkStereoDisplay_ConnectLinks(pObj);
       status = System_linkCreate(pObj->NullSourceLinkID, &pObj->NullSourcePrm, sizeof(pObj->NullSourcePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_A15_0_IPU1_0_0LinkID, &pObj->IPCOut_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCOut_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_A15_0_0LinkID, &pObj->IPCIn_IPU1_0_A15_0_0Prm, sizeof(pObj->IPCIn_IPU1_0_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->DecodeLinkID, &pObj->DecodePrm, sizeof(pObj->DecodePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_decodeOutLinkID, &pObj->VPE_decodeOutPrm, sizeof(pObj->VPE_decodeOutPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_origLinkID, &pObj->Dup_origPrm, sizeof(pObj->Dup_origPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_dispLinkID, &pObj->Sync_dispPrm, sizeof(pObj->Sync_dispPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_CensusInputLinkID, &pObj->Dup_CensusInputPrm, sizeof(pObj->Dup_CensusInputPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE2_0LinkID, &pObj->IPCOut_IPU1_0_EVE2_0Prm, sizeof(pObj->IPCOut_IPU1_0_EVE2_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE2_IPU1_0_0LinkID, &pObj->IPCIn_EVE2_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE2_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_CensusLinkID, &pObj->Alg_CensusPrm, sizeof(pObj->Alg_CensusPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE2_EVE3_0LinkID, &pObj->IPCOut_EVE2_EVE3_0Prm, sizeof(pObj->IPCOut_EVE2_EVE3_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE3_EVE2_0LinkID, &pObj->IPCIn_EVE3_EVE2_0Prm, sizeof(pObj->IPCIn_EVE3_EVE2_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DisparityHamDistLinkID, &pObj->Alg_DisparityHamDistPrm, sizeof(pObj->Alg_DisparityHamDistPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE3_IPU1_0_0LinkID, &pObj->IPCOut_EVE3_IPU1_0_0Prm, sizeof(pObj->IPCOut_EVE3_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_EVE3_1LinkID, &pObj->IPCIn_IPU1_0_EVE3_1Prm, sizeof(pObj->IPCIn_IPU1_0_EVE3_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->MergeLinkID, &pObj->MergePrm, sizeof(pObj->MergePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP1_1LinkID, &pObj->IPCOut_IPU1_0_DSP1_1Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_IPU1_0_0LinkID, &pObj->IPCIn_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_StereoPostProcessLinkID, &pObj->Alg_StereoPostProcessPrm, sizeof(pObj->Alg_StereoPostProcessPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_IPU1_0_0LinkID, &pObj->IPCOut_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCOut_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP1_2LinkID, &pObj->IPCIn_IPU1_0_DSP1_2Prm, sizeof(pObj->IPCIn_IPU1_0_DSP1_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_disparityLinkID, &pObj->VPE_disparityPrm, sizeof(pObj->VPE_disparityPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_disparityLinkID, &pObj->Display_disparityPrm, sizeof(pObj->Display_disparityPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_orgdispLinkID, &pObj->VPE_orgdispPrm, sizeof(pObj->VPE_orgdispPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_orgLinkID, &pObj->Sync_orgPrm, sizeof(pObj->Sync_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMsLinkID, &pObj->Alg_DmaSwMsPrm, sizeof(pObj->Alg_DmaSwMsPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_orgLinkID, &pObj->Display_orgPrm, sizeof(pObj->Display_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_networkStereoDisplay_Start(chains_networkStereoDisplayObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_orgdispLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_disparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_disparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP1_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_StereoPostProcessLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->MergeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_EVE3_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE3_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DisparityHamDistLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE3_EVE2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE2_EVE3_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_CensusLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_CensusInputLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_dispLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_origLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_decodeOutLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->NullSourceLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_networkStereoDisplay_Stop(chains_networkStereoDisplayObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_orgdispLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_disparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_disparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_DSP1_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_StereoPostProcessLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->MergeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_EVE3_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE3_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DisparityHamDistLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE3_EVE2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE2_EVE3_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_CensusLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_CensusInputLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_dispLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_origLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_decodeOutLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->NullSourceLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_networkStereoDisplay_Delete(chains_networkStereoDisplayObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_orgdispLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_disparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_disparityLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_DSP1_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_StereoPostProcessLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->MergeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_EVE3_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE3_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DisparityHamDistLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE3_EVE2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE2_EVE3_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_CensusLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_CensusInputLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_dispLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_origLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_decodeOutLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->NullSourceLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_networkStereoDisplay_printBufferStatistics(chains_networkStereoDisplayObj *pObj){
       System_linkPrintBufferStatistics(pObj->NullSourceLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->DecodeLinkID);
       System_linkPrintBufferStatistics(pObj->VPE_decodeOutLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_origLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_dispLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_CensusInputLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE2_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_CensusLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE2_EVE3_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE3_EVE2_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DisparityHamDistLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE3_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_EVE3_1LinkID);
       System_linkPrintBufferStatistics(pObj->MergeLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_StereoPostProcessLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_DSP1_2LinkID);
       System_linkPrintBufferStatistics(pObj->VPE_disparityLinkID);
       System_linkPrintBufferStatistics(pObj->Display_disparityLinkID);
       System_linkPrintBufferStatistics(pObj->VPE_orgdispLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_orgLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintBufferStatistics(pObj->Display_orgLinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_networkStereoDisplay_printStatistics(chains_networkStereoDisplayObj *pObj){
       System_linkPrintStatistics(pObj->NullSourceLinkID);
       System_linkPrintStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       System_linkPrintStatistics(pObj->DecodeLinkID);
       System_linkPrintStatistics(pObj->VPE_decodeOutLinkID);
       System_linkPrintStatistics(pObj->Dup_origLinkID);
       System_linkPrintStatistics(pObj->Sync_dispLinkID);
       System_linkPrintStatistics(pObj->Dup_CensusInputLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE2_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_CensusLinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE2_EVE3_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE3_EVE2_0LinkID);
       System_linkPrintStatistics(pObj->Alg_DisparityHamDistLinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE3_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_EVE3_1LinkID);
       System_linkPrintStatistics(pObj->MergeLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_StereoPostProcessLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_DSP1_2LinkID);
       System_linkPrintStatistics(pObj->VPE_disparityLinkID);
       System_linkPrintStatistics(pObj->Display_disparityLinkID);
       System_linkPrintStatistics(pObj->VPE_orgdispLinkID);
       System_linkPrintStatistics(pObj->Sync_orgLinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintStatistics(pObj->Display_orgLinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

