/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_lvdsVipMultiCam_Display_tda2xx_priv.h"
Void chains_lvdsVipMultiCam_Display_tda2xx_SetLinkId(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){
#ifdef E500_SV_MULTICAM
	pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE;

	pObj->VPELinkID                      = SYSTEM_LINK_ID_VPE_0;

	pObj->SyncLinkID                     = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
	pObj->DupLinkID                      = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);

	pObj->IPCOut_IPU1_0_DSP1_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);	//IPU1_0 -> DSP1_0, in IPU1_0 Core
	pObj->IPCIn_DSP1_IPU1_0_0LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);		//IPU1_0 -> DSP1_0, in DSP1_0 Core
	pObj->Alg_DmaSwMsLinkID              = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
	pObj->IPCOut_DSP1_IPU1_0_0LinkID     = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);	//DSP1_0 -> IPU1_0, in DSP1_0 Core
	pObj->IPCIn_IPU1_0_DSP1_0LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);	//DSP1_0 -> IPU1_0, in IPU1_0 Core

	//pObj->IPCOut_IPU1_0_IPU1_1LinkID	 = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1); //IPU1_0 -> IPU1_1, For Save Link in IPU1_0 Core
	//pObj->IPCIn_IPU1_IPU1_0_1LinkID	 	 = IPU1_1_LINK (SYSTEM_LINK_ID_IPC_IN_0); //IPU1_0 -> IPU1_1, For Save Link in IPU1_1 Core

	pObj->Display_videoLinkID               = SYSTEM_LINK_ID_DISPLAY_0;
	pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
	pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_3;
	//pObj->SaveLinkID					 = IPU1_1_LINK ( SYSTEM_LINT_SAVE_0 ); //ryuhs74@

	Vps_printf("CaptureLinkID : %d\nVPELinkID : %d\nSyncLinkID : %d\nDupLinkID : %d\nIPCOut_IPU1_0_DSP1_0LinkID : %d\nIPCIn_DSP1_IPU1_0_0LinkID : %d\nAlg_DmaSwMsLinkID : %d\nIPCOut_DSP1_IPU1_0_0LinkID : %d\nIPCIn_IPU1_0_DSP1_0LinkID : %d\nDisplay_videoLinkID : %d\nGrpxSrcLinkID : %d\nDisplay_GrpxLinkID : %d\n"
			, pObj->CaptureLinkID
			, pObj->VPELinkID
			, pObj->SyncLinkID
			, pObj->DupLinkID
			, pObj->IPCOut_IPU1_0_DSP1_0LinkID
			, pObj->IPCIn_DSP1_IPU1_0_0LinkID
			, pObj->Alg_DmaSwMsLinkID
			, pObj->IPCOut_DSP1_IPU1_0_0LinkID
			, pObj->IPCIn_IPU1_0_DSP1_0LinkID
			, pObj->Display_videoLinkID
			, pObj->GrpxSrcLinkID
			, pObj->Display_GrpxLinkID);


#else
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE;
       pObj->DupLinkID                      = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->VPELinkID                      = SYSTEM_LINK_ID_VPE_0;
       pObj->SyncLinkID                     = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       //pObj->Alg_DmaSwMsLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->MergeLinkID                    = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->Display_videoLinkID            = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_1;


       pObj->IPCOut_IPU1_0_DSP1_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);	//IPU1_0 -> DSP1_0, in IPU1_0 Core
       pObj->IPCIn_DSP1_IPU1_0_0LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);		//IPU1_0 -> DSP1_0, in DSP1_0 Core
       pObj->Alg_DmaSwMsLinkID              = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP1_IPU1_0_0LinkID     = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);	//DSP1_0 -> IPU1_0, in DSP1_0 Core
       pObj->IPCIn_IPU1_0_DSP1_0LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);	//DSP1_0 -> IPU1_0, in IPU1_0 Core

       Vps_printf("CaptureLinkID : %d\nDupLinkID : %d\nVPELinkID : %d\nSyncLinkID : %d\nAlg_DmaSwMsLinkID : %d\nMergeLinkID : %d\nDisplay_videoLinkID : %d\nGrpxSrcLinkID : %d\nDisplay_GrpxLinkID : %d\n"
       			, pObj->CaptureLinkID
       			, pObj->DupLinkID
       			, pObj->VPELinkID
       			, pObj->SyncLinkID
       			, pObj->Alg_DmaSwMsLinkID
       			, pObj->Display_videoLinkID
       			, pObj->GrpxSrcLinkID
       			, pObj->Display_GrpxLinkID);

#endif
}

Void chains_lvdsVipMultiCam_Display_tda2xx_ResetLinkPrms(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){
#ifdef E500_SV_MULTICAM
	CaptureLink_CreateParams_Init(&pObj->CapturePrm);

	VpeLink_CreateParams_Init(&pObj->VPEPrm);

	SyncLink_CreateParams_Init(&pObj->SyncPrm);
	DupLink_CreateParams_Init(&pObj->DupPrm);
    //IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_IPU1_1Prm);	//IPU1_0 -> IPU1_1, For Save Link in IPU1_0 Core
    //IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_IPU1_0_1Prm);	//IPU1_0 -> IPU1_1, For Save Link in IPU1_1 Core
    IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP1_0Prm);	//IPU1_0 -> DSP1_0, For Cammsys LUT Link in IPU1_0 Core
    IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_IPU1_0_0Prm);	//IPU1_0 -> DSP1_0, For Cammsys LUT Link in DSP1_0 Core
    AlgorithmLink_DmaSwMsCreateParams_Init_DSP(&pObj->Alg_DmaSwMsPrm);
    IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_IPU1_0_0Prm);	//DSP1_0 -> IPU1_0, For Cammsys LUT Link in DSP1_0 Core
    IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP1_0Prm);	//DSP1_0 -> IPU1_0, For Cammsys LUT Link in IPU1_0 Core
    DisplayLink_CreateParams_Init(&pObj->Display_videoPrm);
    GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
    DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);

	 //ryuhs74@20151027 - Add Save Link
    //SaveLink_CreateParams_Init(&pObj->SavePrm); //ryuhs74@20151027 - Add Save Link
#else
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       DupLink_CreateParams_Init(&pObj->DupPrm);
       VpeLink_CreateParams_Init(&pObj->VPEPrm);
       SyncLink_CreateParams_Init(&pObj->SyncPrm);
       //AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMsPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP1_0Prm);	//IPU1_0 -> DSP1_0, For Cammsys LUT Link in IPU1_0 Core
	   IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_IPU1_0_0Prm);	//IPU1_0 -> DSP1_0, For Cammsys LUT Link in DSP1_0 Core
	   AlgorithmLink_DmaSwMsCreateParams_Init_DSP(&pObj->Alg_DmaSwMsPrm);
	   IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_IPU1_0_0Prm);	//DSP1_0 -> IPU1_0, For Cammsys LUT Link in DSP1_0 Core
	   IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP1_0Prm);	//DSP1_0 -> IPU1_0, For Cammsys LUT Link in IPU1_0 Core
       MergeLink_CreateParams_Init(&pObj->MergePrm);
       DisplayLink_CreateParams_Init(&pObj->Display_videoPrm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);


#endif

}

Void chains_lvdsVipMultiCam_Display_tda2xx_SetPrms(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){
       (pObj->DupPrm).numOutQue = 2;
#ifndef E500_SV_MULTICAM
       //(pObj->Alg_DmaSwMsPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       //(pObj->Alg_DmaSwMsPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
       (pObj->MergePrm).numInQue = 2;
#endif
}

Void chains_lvdsVipMultiCam_Display_tda2xx_ConnectLinks(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){

#ifdef E500_SV_MULTICAM
#if 1
    //Capture -> Dup
    pObj->CapturePrm.outQueParams.nextLink = pObj->VPELinkID;
   	pObj->VPEPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
   	pObj->VPEPrm.inQueParams.prevLinkQueId = 0;


    //VPE -> Sync
    pObj->VPEPrm.outQueParams[0].nextLink = pObj->SyncLinkID;
    pObj->SyncPrm.inQueParams.prevLinkId = pObj->VPELinkID;
    pObj->SyncPrm.inQueParams.prevLinkQueId = 0;
#else
    //Capture -> Sync_sv_org
    pObj->CapturePrm.outQueParams.nextLink = pObj->SyncLinkID;
    pObj->SyncPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
    pObj->SyncPrm.inQueParams.prevLinkQueId = 0;
#endif
    //Sync_sv -> Dup_sv
    pObj->SyncPrm.outQueParams.nextLink = pObj->DupLinkID;
    pObj->DupPrm.inQueParams.prevLinkId = pObj->SyncLinkID;
    pObj->DupPrm.inQueParams.prevLinkQueId = 0;

    //Dup_sv -> IPCOut_IPU1_0_DSP1_0
    pObj->DupPrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_DSP1_0LinkID;
    pObj->IPCOut_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->DupLinkID;
    pObj->IPCOut_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

    //Dup_sv -> IPCOut_IPU1_0_IPU1_1
    //pObj->Dup_svPrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_IPU1_1LinkID;
    // pObj->IPCOut_IPU1_0_IPU1_1Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
    //pObj->IPCOut_IPU1_0_IPU1_1Prm.inQueParams.prevLinkQueId = 1;

    //IPCOut_IPU1_0_DSP1_0 -> IPCIn_DSP1_IPU1_0_0, To Cammsys LUT Link
    pObj->IPCOut_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
    pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP1_0LinkID;
    pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

    //IPCOut_IPU1_0_IPU1_1 -> IPCIn_IPU1_IPU1_0_1, To Save Link
    //pObj->IPCOut_IPU1_0_IPU1_1Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_IPU1_0_1LinkID;
    //pObj->IPCIn_IPU1_IPU1_0_1Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_IPU1_1LinkID;
    // pObj->IPCIn_IPU1_IPU1_0_1Prm.inQueParams.prevLinkQueId = 0;

    //Connect IPCIn_DSP1_IPU1_0_0 and Cammsys LUT Link
    pObj->IPCIn_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_DmaSwMsLinkID;//CammsysLUTLinkID;
    pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkId = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
    pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkQueId = 0;

    //Connect Cammsys LUT Link and IPCOut_DSP1_IPU1_0_0
    pObj->Alg_DmaSwMsPrm.outQueParams.nextLink = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
    pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_DmaSwMsLinkID;
    pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

    //Connect IPCIn_IPU1_IPU1_0_1 and Save Link, Save Link End Link
    // pObj->IPCIn_IPU1_IPU1_0_1Prm.outQueParams.nextLink = pObj->SaveLinkID;
    //pObj->SavePrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_IPU1_0_1LinkID;
    //pObj->SavePrm.inQueParams.prevLinkQueId = 0;

    //IPCOut_DSP1_IPU1_0_0 -> IPCIn_IPU1_0_DSP1_0
    pObj->IPCOut_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
    pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
    pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

    //IPCIn_IPU1_0_DSP1_0 -> Display_sv
    pObj->IPCIn_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->Display_videoLinkID;
    pObj->Display_videoPrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
    pObj->Display_videoPrm.inQueParams.prevLinkQueId = 0;

    //GrpxSrc -> Display_Grpx
    pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
    pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
    pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;


//    gGrpxSrcLinkID = pObj->GrpxSrcLinkID; //ryuyhs74220151105 - CMD 를 위해 연결
#else
       //Capture -> Dup
       pObj->CapturePrm.outQueParams.nextLink = pObj->DupLinkID;
       pObj->DupPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->DupPrm.inQueParams.prevLinkQueId = 0;

       //Dup -> VPE
       pObj->DupPrm.outQueParams[0].nextLink = pObj->VPELinkID;
       pObj->VPEPrm.inQueParams.prevLinkId = pObj->DupLinkID;
       pObj->VPEPrm.inQueParams.prevLinkQueId = 0;

       //Dup -> Merge
       pObj->DupPrm.outQueParams[1].nextLink = pObj->MergeLinkID;
       pObj->MergePrm.inQueParams[1].prevLinkId = pObj->DupLinkID;
       pObj->MergePrm.inQueParams[1].prevLinkQueId = 1;

       //Dup -> Save //ryuhs74@20151028 - Add Save Link
       //pObj->DupPrm.outQueParams[2].nextLink = pObj->SyncLinkID;
       //pObj->Save_Prm.inQueParams.prevLinkId = pObj->DupLinkID;
       //pObj->Save_Prm.inQueParams.prevLinkQueId = 2;

       //VPE -> Sync
       pObj->VPEPrm.outQueParams[0].nextLink = pObj->SyncLinkID;
       pObj->SyncPrm.inQueParams.prevLinkId = pObj->VPELinkID;
       pObj->SyncPrm.inQueParams.prevLinkQueId = 0;
#if 0


       //Sync -> Alg_DmaSwMs
       pObj->SyncPrm.outQueParams.nextLink = pObj->Alg_DmaSwMsLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkId = pObj->SyncLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs -> Merge
       pObj->Alg_DmaSwMsPrm.outQueParams.nextLink = pObj->MergeLinkID;
       pObj->MergePrm.inQueParams[0].prevLinkId = pObj->Alg_DmaSwMsLinkID;
       pObj->MergePrm.inQueParams[0].prevLinkQueId = 0;
#else
       //sysnc -> IPCOUT
       pObj->SyncPrm.outQueParams.nextLink = pObj->IPCOut_IPU1_0_DSP1_0LinkID;
       pObj->IPCOut_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->SyncLinkID;
       pObj->IPCOut_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOU->IPcIN
       pObj->IPCOut_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP1_0LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIN -> Alg
       pObj->IPCIn_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_DmaSwMsLinkID;//CammsysLUTLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkId = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkQueId = 0;

       //ALG->IPCOUT
       pObj->Alg_DmaSwMsPrm.outQueParams.nextLink = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_DmaSwMsLinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;



          //IPCOut_DSP1_IPU1_0_0 -> IPCIn_IPU1_0_DSP1_0
          pObj->IPCOut_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
          pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
          pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

          //IPCIn_IPU1_0_DSP1_0 -> Merhe
          pObj->IPCIn_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->MergeLinkID;
          pObj->MergePrm.inQueParams[0].prevLinkId = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
          pObj->MergePrm.inQueParams[0].prevLinkQueId = 0;
       //IPCOUT -> IPCIN
       //IPCIN -> Merge
#endif
       //Merge -> Display_video
       pObj->MergePrm.outQueParams.nextLink = pObj->Display_videoLinkID;
       pObj->Display_videoPrm.inQueParams.prevLinkId = pObj->MergeLinkID;
       pObj->Display_videoPrm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;
#endif


}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_Create(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj, Void *appObj){

       Int32 status;

       chains_lvdsVipMultiCam_Display_tda2xx_SetLinkId(pObj);
       chains_lvdsVipMultiCam_Display_tda2xx_ResetLinkPrms(pObj);

       chains_lvdsVipMultiCam_Display_tda2xx_SetPrms(pObj);
       chains_lvdsVipMultiCam_Display_tda2xx_SetAppPrms(pObj, appObj);

       chains_lvdsVipMultiCam_Display_tda2xx_ConnectLinks(pObj);
#ifdef E500_SV_MULTICAM
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //test
	   status = System_linkCreate(pObj->VPELinkID, &pObj->VPEPrm, sizeof(pObj->VPEPrm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkCreate(pObj->SyncLinkID, &pObj->SyncPrm, sizeof(pObj->SyncPrm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkCreate(pObj->DupLinkID, &pObj->DupPrm, sizeof(pObj->DupPrm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //IPU1_0 -> DSP1_0, For Cammsys LUT Link in IPU1_0 Core
	   status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP1_0LinkID, &pObj->IPCOut_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_0Prm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //IPU1_0 -> DSP1_0, For Cammsys LUT Link in DSP1_0 Core
	   status = System_linkCreate(pObj->IPCIn_DSP1_IPU1_0_0LinkID, &pObj->IPCIn_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_0Prm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //Cammsys LUT Link Start
	   status = System_linkCreate(pObj->Alg_DmaSwMsLinkID/*CammsysLUT*/, &pObj->Alg_DmaSwMsPrm/*CammsysLUTPrm*/, sizeof(pObj->Alg_DmaSwMsPrm/*CammsysLUTPrm*/));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //DSP1_0 -> IPU1_0, For Cammsys LUT Link in DSP1_0 Core
	   status = System_linkCreate(pObj->IPCOut_DSP1_IPU1_0_0LinkID, &pObj->IPCOut_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCOut_DSP1_IPU1_0_0Prm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //DSP1_0 -> IPU1_0, For Cammsys LUT Link in IPU1_0 Core
	   status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP1_0LinkID, &pObj->IPCIn_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCIn_IPU1_0_DSP1_0Prm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkCreate(pObj->Display_videoLinkID, &pObj->Display_videoPrm, sizeof(pObj->Display_videoPrm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //IPU1_0 -> IPU1_1, For Save Link in IPU1_0 Core
	   // status = System_linkCreate(pObj->IPCOut_IPU1_0_IPU1_1LinkID, &pObj->IPCOut_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_0Prm));
	   // UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //IPU1_0 -> IPU1_1, For Save Link in IPU1_1 Core
	   // status = System_linkCreate(pObj->IPCIn_IPU1_IPU1_0_1LinkID, &pObj->IPCIn_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_0Prm));
       //  UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //status = System_linkCreate(pObj->SaveLinkID, &pObj->SavePrm, sizeof(pObj->SavePrm));
	   //UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#else
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->DupLinkID, &pObj->DupPrm, sizeof(pObj->DupPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPELinkID, &pObj->VPEPrm, sizeof(pObj->VPEPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SyncLinkID, &pObj->SyncPrm, sizeof(pObj->SyncPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       //IPU1_0 -> DSP1_0, For Cammsys LUT Link in IPU1_0 Core
       	   status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP1_0LinkID, &pObj->IPCOut_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_0Prm));
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       	   //IPU1_0 -> DSP1_0, For Cammsys LUT Link in DSP1_0 Core
       	   status = System_linkCreate(pObj->IPCIn_DSP1_IPU1_0_0LinkID, &pObj->IPCIn_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_0Prm));
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       	   //Cammsys LUT Link Start
       	   status = System_linkCreate(pObj->Alg_DmaSwMsLinkID/*CammsysLUT*/, &pObj->Alg_DmaSwMsPrm/*CammsysLUTPrm*/, sizeof(pObj->Alg_DmaSwMsPrm/*CammsysLUTPrm*/));
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       	   //DSP1_0 -> IPU1_0, For Cammsys LUT Link in DSP1_0 Core
       	   status = System_linkCreate(pObj->IPCOut_DSP1_IPU1_0_0LinkID, &pObj->IPCOut_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCOut_DSP1_IPU1_0_0Prm));
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       	   //DSP1_0 -> IPU1_0, For Cammsys LUT Link in IPU1_0 Core
       	   status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP1_0LinkID, &pObj->IPCIn_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCIn_IPU1_0_DSP1_0Prm));
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       //status = System_linkCreate(pObj->Alg_DmaSwMsLinkID, &pObj->Alg_DmaSwMsPrm, sizeof(pObj->Alg_DmaSwMsPrm));
       //UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->MergeLinkID, &pObj->MergePrm, sizeof(pObj->MergePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_videoLinkID, &pObj->Display_videoPrm, sizeof(pObj->Display_videoPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#endif
       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_Start(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){

       Int32 status;
#ifdef E500_SV_MULTICAM

       status = System_linkStart(pObj->Display_GrpxLinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->GrpxSrcLinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->Display_videoLinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //IPCOut_DSP1_IPU1_0_0Prm
	   status = System_linkStart(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);


	   status = System_linkStart(pObj->Alg_DmaSwMsLinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->IPCOut_IPU1_0_DSP1_0LinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);



	   //status = System_linkStart(pObj->VPELinkID);
	  // UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->DupLinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->SyncLinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   //test
	   status = System_linkStart(pObj->VPELinkID);
	          UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	   status = System_linkStart(pObj->CaptureLinkID);
	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);





	          //Save Link Start
	          //status = System_linkStart(pObj->SaveLinkID);
	          //UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	          //Save Link Start
	          //status = System_linkStart(pObj->IPCIn_IPU1_IPU1_0_1LinkID);
	         // UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

	          //Save Link Start
	         // status = System_linkStart(pObj->IPCOut_IPU1_0_IPU1_1LinkID);
	         // UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);


#else
       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_videoLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->MergeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       //status = System_linkStart(pObj->Alg_DmaSwMsLinkID);
       //UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       	   //IPCOut_DSP1_IPU1_0_0Prm
       	   status = System_linkStart(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);


       	   status = System_linkStart(pObj->Alg_DmaSwMsLinkID);
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       	   status = System_linkStart(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       	   status = System_linkStart(pObj->IPCOut_IPU1_0_DSP1_0LinkID);
       	   UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);



       status = System_linkStart(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->DupLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#endif

       //ryyuhs74@20151028 - Add Save Link
       //status = System_linkStart(pObj->Save_SaveLinkID);
       //UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_Stop(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_videoLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

#ifndef E500_SV_MULTICAM
       status = System_linkStop(pObj->MergeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#endif

       status = System_linkStop(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

#ifndef E500_SV_MULTICAM
       status = System_linkStop(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#endif

       status = System_linkStop(pObj->DupLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_Delete(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_videoLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#ifndef E500_SV_MULTICAM
       status = System_linkDelete(pObj->MergeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#endif
       status = System_linkDelete(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#ifndef E500_SV_MULTICAM
       status = System_linkDelete(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);
#endif
       status = System_linkDelete(pObj->DupLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_lvdsVipMultiCam_Display_tda2xx_printBufferStatistics(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->DupLinkID);
#ifndef E500_SV_MULTICAM
       System_linkPrintBufferStatistics(pObj->VPELinkID);
#endif
       System_linkPrintBufferStatistics(pObj->SyncLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMsLinkID);
#ifndef E500_SV_MULTICAM
       System_linkPrintBufferStatistics(pObj->MergeLinkID);
#endif
       System_linkPrintBufferStatistics(pObj->Display_videoLinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_lvdsVipMultiCam_Display_tda2xx_printStatistics(chains_lvdsVipMultiCam_Display_tda2xxObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->DupLinkID);
#ifndef E500_SV_MULTICAM
       System_linkPrintStatistics(pObj->VPELinkID);
#endif
       System_linkPrintStatistics(pObj->SyncLinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMsLinkID);
#ifndef E500_SV_MULTICAM
       System_linkPrintStatistics(pObj->MergeLinkID);
#endif
       System_linkPrintStatistics(pObj->Display_videoLinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

