/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraFullView_H_
#define _chains_vipSingleCameraFullView_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_fullView.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    Alg_FullViewLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_VideoLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       AlgorithmLink_FullViewCreateParams     Alg_FullViewPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_VideoPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraFullViewObj;

Void chains_vipSingleCameraFullView_SetLinkId(chains_vipSingleCameraFullViewObj *pObj);

Void chains_vipSingleCameraFullView_ResetLinkPrms(chains_vipSingleCameraFullViewObj *pObj);

Void chains_vipSingleCameraFullView_SetPrms(chains_vipSingleCameraFullViewObj *pObj);

Void chains_vipSingleCameraFullView_ConnectLinks(chains_vipSingleCameraFullViewObj *pObj);

Int32 chains_vipSingleCameraFullView_Create(chains_vipSingleCameraFullViewObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraFullView_Start(chains_vipSingleCameraFullViewObj *pObj);

Int32 chains_vipSingleCameraFullView_Stop(chains_vipSingleCameraFullViewObj *pObj);

Int32 chains_vipSingleCameraFullView_Delete(chains_vipSingleCameraFullViewObj *pObj);

Void chains_vipSingleCameraFullView_printBufferStatistics(chains_vipSingleCameraFullViewObj *pObj);

Void chains_vipSingleCameraFullView_printStatistics(chains_vipSingleCameraFullViewObj *pObj);

Void chains_vipSingleCameraFullView_SetAppPrms(chains_vipSingleCameraFullViewObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraFullView_H_ */
