/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCam_DualDisplay_H_
#define _chains_vipSingleCam_DualDisplay_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    Dup_CaptureLinkID;
       UInt32    Display_HDMILinkID;
       UInt32    Display_LCDLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       DupLink_CreateParams                    Dup_CapturePrm;
       DisplayLink_CreateParams                Display_HDMIPrm;
       DisplayLink_CreateParams                Display_LCDPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCam_DualDisplayObj;

Void chains_vipSingleCam_DualDisplay_SetLinkId(chains_vipSingleCam_DualDisplayObj *pObj);

Void chains_vipSingleCam_DualDisplay_ResetLinkPrms(chains_vipSingleCam_DualDisplayObj *pObj);

Void chains_vipSingleCam_DualDisplay_SetPrms(chains_vipSingleCam_DualDisplayObj *pObj);

Void chains_vipSingleCam_DualDisplay_ConnectLinks(chains_vipSingleCam_DualDisplayObj *pObj);

Int32 chains_vipSingleCam_DualDisplay_Create(chains_vipSingleCam_DualDisplayObj *pObj, Void *appObj);

Int32 chains_vipSingleCam_DualDisplay_Start(chains_vipSingleCam_DualDisplayObj *pObj);

Int32 chains_vipSingleCam_DualDisplay_Stop(chains_vipSingleCam_DualDisplayObj *pObj);

Int32 chains_vipSingleCam_DualDisplay_Delete(chains_vipSingleCam_DualDisplayObj *pObj);

Void chains_vipSingleCam_DualDisplay_printBufferStatistics(chains_vipSingleCam_DualDisplayObj *pObj);

Void chains_vipSingleCam_DualDisplay_printStatistics(chains_vipSingleCam_DualDisplayObj *pObj);

Void chains_vipSingleCam_DualDisplay_SetAppPrms(chains_vipSingleCam_DualDisplayObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCam_DualDisplay_H_ */
