/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_lvdsVipSurroundViewAnalyticsUltrasound_priv.h"
Void chains_lvdsVipSurroundViewAnalyticsUltrasound_SetLinkId(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE;
       pObj->SelectLinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_SELECT_0);
       pObj->VPE_algPdLinkID                = SYSTEM_LINK_ID_VPE_0;
       pObj->Dup_algPdLinkID                = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_3);
       pObj->IPCOut_IPU1_0_EVE1_3LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_3);
       pObj->IPCIn_EVE1_IPU1_0_0LinkID      = EVE1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_FeaturePlaneComputationLinkID = EVE1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE1_DSP2_0LinkID       = EVE1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP2_EVE1_3LinkID        = DSP2_LINK (SYSTEM_LINK_ID_IPC_IN_3);
       pObj->Alg_ObjectDetectionLinkID      = DSP2_LINK (SYSTEM_LINK_ID_ALG_3);
       pObj->IPCOut_DSP2_IPU1_0_2LinkID     = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_IPU1_0_DSP2_1LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->Merge_algPdLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->Sync_algPdLinkID               = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_2);
       pObj->Dup_objDrawLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_4);
       pObj->Alg_ObjectDraw_TsrLinkID       = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_2);
       pObj->Alg_ObjectDraw_PdLinkID        = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->Merge_alg_displayLinkID        = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_1);
       pObj->Sync_algDisplayLinkID          = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_3);
       pObj->Alg_DmaSwMs_algLinkID          = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_3);
       pObj->Display_algLinkID              = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->Dup_sv_orgLinkID               = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->Sync_svLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_1);
       pObj->Dup_svLinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_1);
       pObj->IPCOut_IPU1_0_DSP1_1LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_DSP1_IPU1_0_0LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->IPCOut_IPU1_0_DSP2_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP2_IPU1_0_0LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_GeoAlignLinkID             = DSP2_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP2_DSP1_0LinkID       = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP1_DSP2_1LinkID        = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->Alg_SynthesisLinkID            = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP1_DSP2_1LinkID       = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_DSP2_DSP1_1LinkID        = DSP2_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->Alg_PhotoAlignLinkID           = DSP2_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->IPCOut_DSP2_DSP1_1LinkID       = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_DSP1_DSP2_2LinkID        = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->IPCOut_DSP1_IPU1_0_0LinkID     = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_DSP1_0LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Display_svLinkID               = SYSTEM_LINK_ID_DISPLAY_1;
       pObj->VPE_sv_orgLinkID               = SYSTEM_LINK_ID_VPE_1;
       pObj->Sync_sv_orgLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_DmaSwMs_sv_orgLinkID       = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->Display_sv_orgLinkID           = SYSTEM_LINK_ID_DISPLAY_2;
       pObj->UltrasonicCaptureLinkID        = SYSTEM_LINK_ID_ULTRASONIC_CAPTURE;
       pObj->Dup_usLinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_2);
       pObj->IPCOut_IPU1_0_DSP2_2LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_DSP2_IPU1_0_2LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->Alg_UltrasonicFusionLinkID     = DSP2_LINK (SYSTEM_LINK_ID_ALG_2);
       pObj->IPCOut_DSP2_IPU1_0_3LinkID     = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_3);
       pObj->IPCIn_IPU1_0_DSP2_2LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_3;
       pObj->NullLinkID                     = DSP2_LINK (SYSTEM_LINK_ID_NULL_0);
}

Void chains_lvdsVipSurroundViewAnalyticsUltrasound_ResetLinkPrms(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       SelectLink_CreateParams_Init(&pObj->SelectPrm);
       VpeLink_CreateParams_Init(&pObj->VPE_algPdPrm);
       DupLink_CreateParams_Init(&pObj->Dup_algPdPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE1_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE1_IPU1_0_0Prm);
       AlgorithmLink_FeatureComputation_Init(&pObj->Alg_FeaturePlaneComputationPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE1_DSP2_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP2_EVE1_3Prm);
       AlgorithmLink_ObjectDetection_Init(&pObj->Alg_ObjectDetectionPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_IPU1_0_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP2_1Prm);
       MergeLink_CreateParams_Init(&pObj->Merge_algPdPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_algPdPrm);
       DupLink_CreateParams_Init(&pObj->Dup_objDrawPrm);
       AlgorithmLink_ObjectDraw_Init(&pObj->Alg_ObjectDraw_TsrPrm);
       AlgorithmLink_ObjectDraw_Init(&pObj->Alg_ObjectDraw_PdPrm);
       MergeLink_CreateParams_Init(&pObj->Merge_alg_displayPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_algDisplayPrm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMs_algPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_algPrm);
       DupLink_CreateParams_Init(&pObj->Dup_sv_orgPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_svPrm);
       DupLink_CreateParams_Init(&pObj->Dup_svPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP1_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP2_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP2_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_DSP1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_DSP2_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_DSP2_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP2_DSP1_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_DSP1_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_DSP2_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP1_0Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_svPrm);
       VpeLink_CreateParams_Init(&pObj->VPE_sv_orgPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_sv_orgPrm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMs_sv_orgPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_sv_orgPrm);
       UltrasonicCaptureLink_CreateParams_Init(&pObj->UltrasonicCapturePrm);
       DupLink_CreateParams_Init(&pObj->Dup_usPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP2_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP2_IPU1_0_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_IPU1_0_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP2_2Prm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
       NullLink_CreateParams_Init (&pObj->NullPrm);
}

Void chains_lvdsVipSurroundViewAnalyticsUltrasound_SetPrms(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){
       (pObj->SelectPrm).numOutQue = 2;
       (pObj->Dup_algPdPrm).numOutQue = 2;
       (pObj->Alg_FeaturePlaneComputationPrm).baseClassCreate.size  = sizeof(AlgorithmLink_FeaturePlaneComputationCreateParams);
       (pObj->Alg_FeaturePlaneComputationPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_FEATUREPLANECOMPUTE;
       (pObj->Alg_ObjectDetectionPrm).baseClassCreate.size  = sizeof(AlgorithmLink_ObjectDetectionCreateParams);
       (pObj->Alg_ObjectDetectionPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_OBJECTDETECTION;
       (pObj->Merge_algPdPrm).numInQue = 2;
       (pObj->Dup_objDrawPrm).numOutQue = 2;
       (pObj->Alg_ObjectDraw_TsrPrm).baseClassCreate.size  = sizeof(AlgorithmLink_ObjectDrawCreateParams);
       (pObj->Alg_ObjectDraw_TsrPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_PD_DRAW;
       (pObj->Alg_ObjectDraw_PdPrm).baseClassCreate.size  = sizeof(AlgorithmLink_ObjectDrawCreateParams);
       (pObj->Alg_ObjectDraw_PdPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_PD_DRAW;
       (pObj->Merge_alg_displayPrm).numInQue = 2;
       (pObj->Alg_DmaSwMs_algPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMs_algPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
       (pObj->Dup_sv_orgPrm).numOutQue = 2;
       (pObj->Dup_svPrm).numOutQue = 2;
       (pObj->Alg_GeoAlignPrm).baseClassCreate.size  = sizeof(AlgorithmLink_GAlignCreateParams);
       (pObj->Alg_GeoAlignPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_GALIGNMENT;
       (pObj->Alg_SynthesisPrm).baseClassCreate.size  = sizeof(AlgorithmLink_SynthesisCreateParams);
       (pObj->Alg_SynthesisPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_SYNTHESIS;
       (pObj->Alg_PhotoAlignPrm).baseClassCreate.size  = sizeof(AlgorithmLink_PAlignCreateParams);
       (pObj->Alg_PhotoAlignPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_PALIGNMENT;
       (pObj->Alg_DmaSwMs_sv_orgPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMs_sv_orgPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
       (pObj->Dup_usPrm).numOutQue = 1;
       (pObj->Alg_UltrasonicFusionPrm).baseClassCreate.size  = sizeof(AlgorithmLink_UltrasonicFusionCreateParams);
       (pObj->Alg_UltrasonicFusionPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_ULTRASONICFUSION;
       (pObj->NullPrm).numInQue = 1;
}

Void chains_lvdsVipSurroundViewAnalyticsUltrasound_ConnectLinks(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){

       //Capture -> Select
       pObj->CapturePrm.outQueParams.nextLink = pObj->SelectLinkID;
       pObj->SelectPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->SelectPrm.inQueParams.prevLinkQueId = 0;

       //Select -> Dup_sv_org
       pObj->SelectPrm.outQueParams[0].nextLink = pObj->Dup_sv_orgLinkID;
       pObj->Dup_sv_orgPrm.inQueParams.prevLinkId = pObj->SelectLinkID;
       pObj->Dup_sv_orgPrm.inQueParams.prevLinkQueId = 0;

       //Select -> VPE_algPd
       pObj->SelectPrm.outQueParams[1].nextLink = pObj->VPE_algPdLinkID;
       pObj->VPE_algPdPrm.inQueParams.prevLinkId = pObj->SelectLinkID;
       pObj->VPE_algPdPrm.inQueParams.prevLinkQueId = 1;

       //VPE_algPd -> Dup_algPd
       pObj->VPE_algPdPrm.outQueParams[0].nextLink = pObj->Dup_algPdLinkID;
       pObj->Dup_algPdPrm.inQueParams.prevLinkId = pObj->VPE_algPdLinkID;
       pObj->Dup_algPdPrm.inQueParams.prevLinkQueId = 0;

       //Dup_algPd -> Merge_algPd
       pObj->Dup_algPdPrm.outQueParams[0].nextLink = pObj->Merge_algPdLinkID;
       pObj->Merge_algPdPrm.inQueParams[0].prevLinkId = pObj->Dup_algPdLinkID;
       pObj->Merge_algPdPrm.inQueParams[0].prevLinkQueId = 0;

       //Dup_algPd -> IPCOut_IPU1_0_EVE1_3
       pObj->Dup_algPdPrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_EVE1_3LinkID;
       pObj->IPCOut_IPU1_0_EVE1_3Prm.inQueParams.prevLinkId = pObj->Dup_algPdLinkID;
       pObj->IPCOut_IPU1_0_EVE1_3Prm.inQueParams.prevLinkQueId = 1;

       //IPCOut_IPU1_0_EVE1_3 -> IPCIn_EVE1_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE1_3Prm.outQueParams.nextLink = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE1_3LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE1_IPU1_0_0 -> Alg_FeaturePlaneComputation
       pObj->IPCIn_EVE1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_FeaturePlaneComputationLinkID;
       pObj->Alg_FeaturePlaneComputationPrm.inQueParams.prevLinkId = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->Alg_FeaturePlaneComputationPrm.inQueParams.prevLinkQueId = 0;

       //Alg_FeaturePlaneComputation -> IPCOut_EVE1_DSP2_0
       pObj->Alg_FeaturePlaneComputationPrm.outQueParams.nextLink = pObj->IPCOut_EVE1_DSP2_0LinkID;
       pObj->IPCOut_EVE1_DSP2_0Prm.inQueParams.prevLinkId = pObj->Alg_FeaturePlaneComputationLinkID;
       pObj->IPCOut_EVE1_DSP2_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE1_DSP2_0 -> IPCIn_DSP2_EVE1_3
       pObj->IPCOut_EVE1_DSP2_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP2_EVE1_3LinkID;
       pObj->IPCIn_DSP2_EVE1_3Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE1_DSP2_0LinkID;
       pObj->IPCIn_DSP2_EVE1_3Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP2_EVE1_3 -> Alg_ObjectDetection
       pObj->IPCIn_DSP2_EVE1_3Prm.outQueParams.nextLink = pObj->Alg_ObjectDetectionLinkID;
       pObj->Alg_ObjectDetectionPrm.inQueParams.prevLinkId = pObj->IPCIn_DSP2_EVE1_3LinkID;
       pObj->Alg_ObjectDetectionPrm.inQueParams.prevLinkQueId = 0;

       //Alg_ObjectDetection -> IPCOut_DSP2_IPU1_0_2
       pObj->Alg_ObjectDetectionPrm.outQueParams.nextLink = pObj->IPCOut_DSP2_IPU1_0_2LinkID;
       pObj->IPCOut_DSP2_IPU1_0_2Prm.inQueParams.prevLinkId = pObj->Alg_ObjectDetectionLinkID;
       pObj->IPCOut_DSP2_IPU1_0_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP2_IPU1_0_2 -> IPCIn_IPU1_0_DSP2_1
       pObj->IPCOut_DSP2_IPU1_0_2Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP2_1LinkID;
       pObj->IPCIn_IPU1_0_DSP2_1Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_IPU1_0_2LinkID;
       pObj->IPCIn_IPU1_0_DSP2_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_DSP2_1 -> Merge_algPd
       pObj->IPCIn_IPU1_0_DSP2_1Prm.outQueParams.nextLink = pObj->Merge_algPdLinkID;
       pObj->Merge_algPdPrm.inQueParams[1].prevLinkId = pObj->IPCIn_IPU1_0_DSP2_1LinkID;
       pObj->Merge_algPdPrm.inQueParams[1].prevLinkQueId = 0;

       //Merge_algPd -> Sync_algPd
       pObj->Merge_algPdPrm.outQueParams.nextLink = pObj->Sync_algPdLinkID;
       pObj->Sync_algPdPrm.inQueParams.prevLinkId = pObj->Merge_algPdLinkID;
       pObj->Sync_algPdPrm.inQueParams.prevLinkQueId = 0;

       //Sync_algPd -> Dup_objDraw
       pObj->Sync_algPdPrm.outQueParams.nextLink = pObj->Dup_objDrawLinkID;
       pObj->Dup_objDrawPrm.inQueParams.prevLinkId = pObj->Sync_algPdLinkID;
       pObj->Dup_objDrawPrm.inQueParams.prevLinkQueId = 0;

       //Dup_objDraw -> Alg_ObjectDraw_Pd
       pObj->Dup_objDrawPrm.outQueParams[0].nextLink = pObj->Alg_ObjectDraw_PdLinkID;
       pObj->Alg_ObjectDraw_PdPrm.inQueParams.prevLinkId = pObj->Dup_objDrawLinkID;
       pObj->Alg_ObjectDraw_PdPrm.inQueParams.prevLinkQueId = 0;

       //Dup_objDraw -> Alg_ObjectDraw_Tsr
       pObj->Dup_objDrawPrm.outQueParams[1].nextLink = pObj->Alg_ObjectDraw_TsrLinkID;
       pObj->Alg_ObjectDraw_TsrPrm.inQueParams.prevLinkId = pObj->Dup_objDrawLinkID;
       pObj->Alg_ObjectDraw_TsrPrm.inQueParams.prevLinkQueId = 1;

       //Alg_ObjectDraw_Tsr -> Merge_alg_display
       pObj->Alg_ObjectDraw_TsrPrm.outQueParams.nextLink = pObj->Merge_alg_displayLinkID;
       pObj->Merge_alg_displayPrm.inQueParams[1].prevLinkId = pObj->Alg_ObjectDraw_TsrLinkID;
       pObj->Merge_alg_displayPrm.inQueParams[1].prevLinkQueId = 0;

       //Alg_ObjectDraw_Pd -> Merge_alg_display
       pObj->Alg_ObjectDraw_PdPrm.outQueParams.nextLink = pObj->Merge_alg_displayLinkID;
       pObj->Merge_alg_displayPrm.inQueParams[0].prevLinkId = pObj->Alg_ObjectDraw_PdLinkID;
       pObj->Merge_alg_displayPrm.inQueParams[0].prevLinkQueId = 0;

       //Merge_alg_display -> Sync_algDisplay
       pObj->Merge_alg_displayPrm.outQueParams.nextLink = pObj->Sync_algDisplayLinkID;
       pObj->Sync_algDisplayPrm.inQueParams.prevLinkId = pObj->Merge_alg_displayLinkID;
       pObj->Sync_algDisplayPrm.inQueParams.prevLinkQueId = 0;

       //Sync_algDisplay -> Alg_DmaSwMs_alg
       pObj->Sync_algDisplayPrm.outQueParams.nextLink = pObj->Alg_DmaSwMs_algLinkID;
       pObj->Alg_DmaSwMs_algPrm.inQueParams.prevLinkId = pObj->Sync_algDisplayLinkID;
       pObj->Alg_DmaSwMs_algPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs_alg -> Display_alg
       pObj->Alg_DmaSwMs_algPrm.outQueParams.nextLink = pObj->Display_algLinkID;
       pObj->Display_algPrm.inQueParams.prevLinkId = pObj->Alg_DmaSwMs_algLinkID;
       pObj->Display_algPrm.inQueParams.prevLinkQueId = 0;

       //Dup_sv_org -> VPE_sv_org
       pObj->Dup_sv_orgPrm.outQueParams[0].nextLink = pObj->VPE_sv_orgLinkID;
       pObj->VPE_sv_orgPrm.inQueParams.prevLinkId = pObj->Dup_sv_orgLinkID;
       pObj->VPE_sv_orgPrm.inQueParams.prevLinkQueId = 0;

       //Dup_sv_org -> Sync_sv
       pObj->Dup_sv_orgPrm.outQueParams[1].nextLink = pObj->Sync_svLinkID;
       pObj->Sync_svPrm.inQueParams.prevLinkId = pObj->Dup_sv_orgLinkID;
       pObj->Sync_svPrm.inQueParams.prevLinkQueId = 1;

       //Sync_sv -> Dup_sv
       pObj->Sync_svPrm.outQueParams.nextLink = pObj->Dup_svLinkID;
       pObj->Dup_svPrm.inQueParams.prevLinkId = pObj->Sync_svLinkID;
       pObj->Dup_svPrm.inQueParams.prevLinkQueId = 0;

       //Dup_sv -> IPCOut_IPU1_0_DSP2_0
       pObj->Dup_svPrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_DSP2_0LinkID;
       pObj->IPCOut_IPU1_0_DSP2_0Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_DSP2_0Prm.inQueParams.prevLinkQueId = 0;

       //Dup_sv -> IPCOut_IPU1_0_DSP1_1
       pObj->Dup_svPrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkQueId = 1;

       //IPCOut_IPU1_0_DSP1_1 -> IPCIn_DSP1_IPU1_0_0
       pObj->IPCOut_IPU1_0_DSP1_1Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_IPU1_0_0 -> Alg_Synthesis
       pObj->IPCIn_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_SynthesisLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->Alg_SynthesisPrm.inQueParams[0].prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP2_0 -> IPCIn_DSP2_IPU1_0_0
       pObj->IPCOut_IPU1_0_DSP2_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP2_IPU1_0_0LinkID;
       pObj->IPCIn_DSP2_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP2_0LinkID;
       pObj->IPCIn_DSP2_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP2_IPU1_0_0 -> Alg_GeoAlign
       pObj->IPCIn_DSP2_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_GeoAlignLinkID;
       pObj->Alg_GeoAlignPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP2_IPU1_0_0LinkID;
       pObj->Alg_GeoAlignPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_GeoAlign -> IPCOut_DSP2_DSP1_0
       pObj->Alg_GeoAlignPrm.outQueParams[0].nextLink = pObj->IPCOut_DSP2_DSP1_0LinkID;
       pObj->IPCOut_DSP2_DSP1_0Prm.inQueParams.prevLinkId = pObj->Alg_GeoAlignLinkID;
       pObj->IPCOut_DSP2_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //Alg_GeoAlign -> Null
       pObj->Alg_GeoAlignPrm.outQueParams[1].nextLink = pObj->NullLinkID;
       pObj->NullPrm.inQueParams[0].prevLinkId = pObj->Alg_GeoAlignLinkID;
       pObj->NullPrm.inQueParams[0].prevLinkQueId = 1;

       //Alg_GeoAlign -> Alg_UltrasonicFusion
       pObj->Alg_GeoAlignPrm.outQueParams[2].nextLink = pObj->Alg_UltrasonicFusionLinkID;
       pObj->Alg_UltrasonicFusionPrm.inQueParams[1].prevLinkId = pObj->Alg_GeoAlignLinkID;
       pObj->Alg_UltrasonicFusionPrm.inQueParams[1].prevLinkQueId = 2;

       //IPCOut_DSP2_DSP1_0 -> IPCIn_DSP1_DSP2_1
       pObj->IPCOut_DSP2_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_DSP2_1LinkID;
       pObj->IPCIn_DSP1_DSP2_1Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_DSP1_0LinkID;
       pObj->IPCIn_DSP1_DSP2_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_DSP2_1 -> Alg_Synthesis
       pObj->IPCIn_DSP1_DSP2_1Prm.outQueParams.nextLink = pObj->Alg_SynthesisLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[1].prevLinkId = pObj->IPCIn_DSP1_DSP2_1LinkID;
       pObj->Alg_SynthesisPrm.inQueParams[1].prevLinkQueId = 0;

       //Alg_Synthesis -> IPCOut_DSP1_IPU1_0_0
       pObj->Alg_SynthesisPrm.outQueParams[0].nextLink = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //Alg_Synthesis -> IPCOut_DSP1_DSP2_1
       pObj->Alg_SynthesisPrm.outQueParams[1].nextLink = pObj->IPCOut_DSP1_DSP2_1LinkID;
       pObj->IPCOut_DSP1_DSP2_1Prm.inQueParams.prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->IPCOut_DSP1_DSP2_1Prm.inQueParams.prevLinkQueId = 1;

       //IPCOut_DSP1_DSP2_1 -> IPCIn_DSP2_DSP1_1
       pObj->IPCOut_DSP1_DSP2_1Prm.outQueParams.nextLink = pObj->IPCIn_DSP2_DSP1_1LinkID;
       pObj->IPCIn_DSP2_DSP1_1Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_DSP2_1LinkID;
       pObj->IPCIn_DSP2_DSP1_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP2_DSP1_1 -> Alg_PhotoAlign
       pObj->IPCIn_DSP2_DSP1_1Prm.outQueParams.nextLink = pObj->Alg_PhotoAlignLinkID;
       pObj->Alg_PhotoAlignPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP2_DSP1_1LinkID;
       pObj->Alg_PhotoAlignPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_PhotoAlign -> IPCOut_DSP2_DSP1_1
       pObj->Alg_PhotoAlignPrm.outQueParams[0].nextLink = pObj->IPCOut_DSP2_DSP1_1LinkID;
       pObj->IPCOut_DSP2_DSP1_1Prm.inQueParams.prevLinkId = pObj->Alg_PhotoAlignLinkID;
       pObj->IPCOut_DSP2_DSP1_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP2_DSP1_1 -> IPCIn_DSP1_DSP2_2
       pObj->IPCOut_DSP2_DSP1_1Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_DSP2_2LinkID;
       pObj->IPCIn_DSP1_DSP2_2Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_DSP1_1LinkID;
       pObj->IPCIn_DSP1_DSP2_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_DSP2_2 -> Alg_Synthesis
       pObj->IPCIn_DSP1_DSP2_2Prm.outQueParams.nextLink = pObj->Alg_SynthesisLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[2].prevLinkId = pObj->IPCIn_DSP1_DSP2_2LinkID;
       pObj->Alg_SynthesisPrm.inQueParams[2].prevLinkQueId = 0;

       //IPCOut_DSP1_IPU1_0_0 -> IPCIn_IPU1_0_DSP1_0
       pObj->IPCOut_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_DSP1_0 -> Display_sv
       pObj->IPCIn_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->Display_svLinkID;
       pObj->Display_svPrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
       pObj->Display_svPrm.inQueParams.prevLinkQueId = 0;

       //VPE_sv_org -> Sync_sv_org
       pObj->VPE_sv_orgPrm.outQueParams[0].nextLink = pObj->Sync_sv_orgLinkID;
       pObj->Sync_sv_orgPrm.inQueParams.prevLinkId = pObj->VPE_sv_orgLinkID;
       pObj->Sync_sv_orgPrm.inQueParams.prevLinkQueId = 0;

       //Sync_sv_org -> Alg_DmaSwMs_sv_org
       pObj->Sync_sv_orgPrm.outQueParams.nextLink = pObj->Alg_DmaSwMs_sv_orgLinkID;
       pObj->Alg_DmaSwMs_sv_orgPrm.inQueParams.prevLinkId = pObj->Sync_sv_orgLinkID;
       pObj->Alg_DmaSwMs_sv_orgPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs_sv_org -> Display_sv_org
       pObj->Alg_DmaSwMs_sv_orgPrm.outQueParams.nextLink = pObj->Display_sv_orgLinkID;
       pObj->Display_sv_orgPrm.inQueParams.prevLinkId = pObj->Alg_DmaSwMs_sv_orgLinkID;
       pObj->Display_sv_orgPrm.inQueParams.prevLinkQueId = 0;

       //UltrasonicCapture -> Dup_us
       pObj->UltrasonicCapturePrm.outQueParams.nextLink = pObj->Dup_usLinkID;
       pObj->Dup_usPrm.inQueParams.prevLinkId = pObj->UltrasonicCaptureLinkID;
       pObj->Dup_usPrm.inQueParams.prevLinkQueId = 0;

       //Dup_us -> IPCOut_IPU1_0_DSP2_2
       pObj->Dup_usPrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_DSP2_2LinkID;
       pObj->IPCOut_IPU1_0_DSP2_2Prm.inQueParams.prevLinkId = pObj->Dup_usLinkID;
       pObj->IPCOut_IPU1_0_DSP2_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP2_2 -> IPCIn_DSP2_IPU1_0_2
       pObj->IPCOut_IPU1_0_DSP2_2Prm.outQueParams.nextLink = pObj->IPCIn_DSP2_IPU1_0_2LinkID;
       pObj->IPCIn_DSP2_IPU1_0_2Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP2_2LinkID;
       pObj->IPCIn_DSP2_IPU1_0_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP2_IPU1_0_2 -> Alg_UltrasonicFusion
       pObj->IPCIn_DSP2_IPU1_0_2Prm.outQueParams.nextLink = pObj->Alg_UltrasonicFusionLinkID;
       pObj->Alg_UltrasonicFusionPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP2_IPU1_0_2LinkID;
       pObj->Alg_UltrasonicFusionPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_UltrasonicFusion -> IPCOut_DSP2_IPU1_0_3
       pObj->Alg_UltrasonicFusionPrm.outQueParams[0].nextLink = pObj->IPCOut_DSP2_IPU1_0_3LinkID;
       pObj->IPCOut_DSP2_IPU1_0_3Prm.inQueParams.prevLinkId = pObj->Alg_UltrasonicFusionLinkID;
       pObj->IPCOut_DSP2_IPU1_0_3Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP2_IPU1_0_3 -> IPCIn_IPU1_0_DSP2_2
       pObj->IPCOut_DSP2_IPU1_0_3Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP2_2LinkID;
       pObj->IPCIn_IPU1_0_DSP2_2Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_IPU1_0_3LinkID;
       pObj->IPCIn_IPU1_0_DSP2_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_DSP2_2 -> GrpxSrc
       pObj->IPCIn_IPU1_0_DSP2_2Prm.outQueParams.nextLink = pObj->GrpxSrcLinkID;
       pObj->GrpxSrcPrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_DSP2_2LinkID;
       pObj->GrpxSrcPrm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_lvdsVipSurroundViewAnalyticsUltrasound_Create(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj, Void *appObj){

       Int32 status;

       chains_lvdsVipSurroundViewAnalyticsUltrasound_SetLinkId(pObj);
       chains_lvdsVipSurroundViewAnalyticsUltrasound_ResetLinkPrms(pObj);

       chains_lvdsVipSurroundViewAnalyticsUltrasound_SetPrms(pObj);
       chains_lvdsVipSurroundViewAnalyticsUltrasound_SetAppPrms(pObj, appObj);

       chains_lvdsVipSurroundViewAnalyticsUltrasound_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SelectLinkID, &pObj->SelectPrm, sizeof(pObj->SelectPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_algPdLinkID, &pObj->VPE_algPdPrm, sizeof(pObj->VPE_algPdPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_algPdLinkID, &pObj->Dup_algPdPrm, sizeof(pObj->Dup_algPdPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE1_3LinkID, &pObj->IPCOut_IPU1_0_EVE1_3Prm, sizeof(pObj->IPCOut_IPU1_0_EVE1_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE1_IPU1_0_0LinkID, &pObj->IPCIn_EVE1_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_FeaturePlaneComputationLinkID, &pObj->Alg_FeaturePlaneComputationPrm, sizeof(pObj->Alg_FeaturePlaneComputationPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE1_DSP2_0LinkID, &pObj->IPCOut_EVE1_DSP2_0Prm, sizeof(pObj->IPCOut_EVE1_DSP2_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP2_EVE1_3LinkID, &pObj->IPCIn_DSP2_EVE1_3Prm, sizeof(pObj->IPCIn_DSP2_EVE1_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_ObjectDetectionLinkID, &pObj->Alg_ObjectDetectionPrm, sizeof(pObj->Alg_ObjectDetectionPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_IPU1_0_2LinkID, &pObj->IPCOut_DSP2_IPU1_0_2Prm, sizeof(pObj->IPCOut_DSP2_IPU1_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP2_1LinkID, &pObj->IPCIn_IPU1_0_DSP2_1Prm, sizeof(pObj->IPCIn_IPU1_0_DSP2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_algPdLinkID, &pObj->Merge_algPdPrm, sizeof(pObj->Merge_algPdPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_algPdLinkID, &pObj->Sync_algPdPrm, sizeof(pObj->Sync_algPdPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_objDrawLinkID, &pObj->Dup_objDrawPrm, sizeof(pObj->Dup_objDrawPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_ObjectDraw_TsrLinkID, &pObj->Alg_ObjectDraw_TsrPrm, sizeof(pObj->Alg_ObjectDraw_TsrPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_ObjectDraw_PdLinkID, &pObj->Alg_ObjectDraw_PdPrm, sizeof(pObj->Alg_ObjectDraw_PdPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_alg_displayLinkID, &pObj->Merge_alg_displayPrm, sizeof(pObj->Merge_alg_displayPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_algDisplayLinkID, &pObj->Sync_algDisplayPrm, sizeof(pObj->Sync_algDisplayPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMs_algLinkID, &pObj->Alg_DmaSwMs_algPrm, sizeof(pObj->Alg_DmaSwMs_algPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_algLinkID, &pObj->Display_algPrm, sizeof(pObj->Display_algPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_sv_orgLinkID, &pObj->Dup_sv_orgPrm, sizeof(pObj->Dup_sv_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_svLinkID, &pObj->Sync_svPrm, sizeof(pObj->Sync_svPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_svLinkID, &pObj->Dup_svPrm, sizeof(pObj->Dup_svPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP1_1LinkID, &pObj->IPCOut_IPU1_0_DSP1_1Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_IPU1_0_0LinkID, &pObj->IPCIn_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP2_0LinkID, &pObj->IPCOut_IPU1_0_DSP2_0Prm, sizeof(pObj->IPCOut_IPU1_0_DSP2_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP2_IPU1_0_0LinkID, &pObj->IPCIn_DSP2_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP2_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_GeoAlignLinkID, &pObj->Alg_GeoAlignPrm, sizeof(pObj->Alg_GeoAlignPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_DSP1_0LinkID, &pObj->IPCOut_DSP2_DSP1_0Prm, sizeof(pObj->IPCOut_DSP2_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_DSP2_1LinkID, &pObj->IPCIn_DSP1_DSP2_1Prm, sizeof(pObj->IPCIn_DSP1_DSP2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_SynthesisLinkID, &pObj->Alg_SynthesisPrm, sizeof(pObj->Alg_SynthesisPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_DSP2_1LinkID, &pObj->IPCOut_DSP1_DSP2_1Prm, sizeof(pObj->IPCOut_DSP1_DSP2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP2_DSP1_1LinkID, &pObj->IPCIn_DSP2_DSP1_1Prm, sizeof(pObj->IPCIn_DSP2_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_PhotoAlignLinkID, &pObj->Alg_PhotoAlignPrm, sizeof(pObj->Alg_PhotoAlignPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_DSP1_1LinkID, &pObj->IPCOut_DSP2_DSP1_1Prm, sizeof(pObj->IPCOut_DSP2_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_DSP2_2LinkID, &pObj->IPCIn_DSP1_DSP2_2Prm, sizeof(pObj->IPCIn_DSP1_DSP2_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_IPU1_0_0LinkID, &pObj->IPCOut_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCOut_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP1_0LinkID, &pObj->IPCIn_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCIn_IPU1_0_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_svLinkID, &pObj->Display_svPrm, sizeof(pObj->Display_svPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_sv_orgLinkID, &pObj->VPE_sv_orgPrm, sizeof(pObj->VPE_sv_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_sv_orgLinkID, &pObj->Sync_sv_orgPrm, sizeof(pObj->Sync_sv_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMs_sv_orgLinkID, &pObj->Alg_DmaSwMs_sv_orgPrm, sizeof(pObj->Alg_DmaSwMs_sv_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_sv_orgLinkID, &pObj->Display_sv_orgPrm, sizeof(pObj->Display_sv_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->UltrasonicCaptureLinkID, &pObj->UltrasonicCapturePrm, sizeof(pObj->UltrasonicCapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_usLinkID, &pObj->Dup_usPrm, sizeof(pObj->Dup_usPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP2_2LinkID, &pObj->IPCOut_IPU1_0_DSP2_2Prm, sizeof(pObj->IPCOut_IPU1_0_DSP2_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP2_IPU1_0_2LinkID, &pObj->IPCIn_DSP2_IPU1_0_2Prm, sizeof(pObj->IPCIn_DSP2_IPU1_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_UltrasonicFusionLinkID, &pObj->Alg_UltrasonicFusionPrm, sizeof(pObj->Alg_UltrasonicFusionPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_IPU1_0_3LinkID, &pObj->IPCOut_DSP2_IPU1_0_3Prm, sizeof(pObj->IPCOut_DSP2_IPU1_0_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP2_2LinkID, &pObj->IPCIn_IPU1_0_DSP2_2Prm, sizeof(pObj->IPCIn_IPU1_0_DSP2_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->NullLinkID, &pObj->NullPrm, sizeof(pObj->NullPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipSurroundViewAnalyticsUltrasound_Start(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_IPU1_0_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_UltrasonicFusionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP2_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_usLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->UltrasonicCaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMs_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP2_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_GeoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMs_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_algDisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_alg_displayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_ObjectDraw_PdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_ObjectDraw_TsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_objDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_ObjectDetectionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP2_EVE1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE1_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_FeaturePlaneComputationLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipSurroundViewAnalyticsUltrasound_Stop(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_IPU1_0_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_UltrasonicFusionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP2_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_usLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->UltrasonicCaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMs_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP2_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_GeoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMs_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_algDisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_alg_displayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_ObjectDraw_PdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_ObjectDraw_TsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_objDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_ObjectDetectionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP2_EVE1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE1_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_FeaturePlaneComputationLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipSurroundViewAnalyticsUltrasound_Delete(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_IPU1_0_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_UltrasonicFusionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP2_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_usLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->UltrasonicCaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMs_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP2_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_GeoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMs_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_algDisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_alg_displayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_ObjectDraw_PdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_ObjectDraw_TsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_objDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_ObjectDetectionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP2_EVE1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE1_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_FeaturePlaneComputationLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_algPdLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_lvdsVipSurroundViewAnalyticsUltrasound_printBufferStatistics(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->SelectLinkID);
       System_linkPrintBufferStatistics(pObj->VPE_algPdLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_algPdLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE1_3LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_FeaturePlaneComputationLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE1_DSP2_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP2_EVE1_3LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_ObjectDetectionLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_IPU1_0_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_DSP2_1LinkID);
       System_linkPrintBufferStatistics(pObj->Merge_algPdLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_algPdLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_objDrawLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_ObjectDraw_TsrLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_ObjectDraw_PdLinkID);
       System_linkPrintBufferStatistics(pObj->Merge_alg_displayLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_algDisplayLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMs_algLinkID);
       System_linkPrintBufferStatistics(pObj->Display_algLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_sv_orgLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_svLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_svLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_GeoAlignLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_DSP2_1LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_SynthesisLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP2_DSP1_1LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_PhotoAlignLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_DSP2_2LinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       System_linkPrintBufferStatistics(pObj->Display_svLinkID);
       System_linkPrintBufferStatistics(pObj->VPE_sv_orgLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_sv_orgLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMs_sv_orgLinkID);
       System_linkPrintBufferStatistics(pObj->Display_sv_orgLinkID);
       System_linkPrintBufferStatistics(pObj->UltrasonicCaptureLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_usLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP2_IPU1_0_2LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_UltrasonicFusionLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_IPU1_0_3LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_DSP2_2LinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->NullLinkID);
       Task_sleep(500);
}

Void chains_lvdsVipSurroundViewAnalyticsUltrasound_printStatistics(chains_lvdsVipSurroundViewAnalyticsUltrasoundObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->SelectLinkID);
       System_linkPrintStatistics(pObj->VPE_algPdLinkID);
       System_linkPrintStatistics(pObj->Dup_algPdLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE1_3LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_FeaturePlaneComputationLinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE1_DSP2_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP2_EVE1_3LinkID);
       System_linkPrintStatistics(pObj->Alg_ObjectDetectionLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_IPU1_0_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_DSP2_1LinkID);
       System_linkPrintStatistics(pObj->Merge_algPdLinkID);
       System_linkPrintStatistics(pObj->Sync_algPdLinkID);
       System_linkPrintStatistics(pObj->Dup_objDrawLinkID);
       System_linkPrintStatistics(pObj->Alg_ObjectDraw_TsrLinkID);
       System_linkPrintStatistics(pObj->Alg_ObjectDraw_PdLinkID);
       System_linkPrintStatistics(pObj->Merge_alg_displayLinkID);
       System_linkPrintStatistics(pObj->Sync_algDisplayLinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMs_algLinkID);
       System_linkPrintStatistics(pObj->Display_algLinkID);
       System_linkPrintStatistics(pObj->Dup_sv_orgLinkID);
       System_linkPrintStatistics(pObj->Sync_svLinkID);
       System_linkPrintStatistics(pObj->Dup_svLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_GeoAlignLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_DSP2_1LinkID);
       System_linkPrintStatistics(pObj->Alg_SynthesisLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP2_DSP1_1LinkID);
       System_linkPrintStatistics(pObj->Alg_PhotoAlignLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_DSP2_2LinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       System_linkPrintStatistics(pObj->Display_svLinkID);
       System_linkPrintStatistics(pObj->VPE_sv_orgLinkID);
       System_linkPrintStatistics(pObj->Sync_sv_orgLinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMs_sv_orgLinkID);
       System_linkPrintStatistics(pObj->Display_sv_orgLinkID);
       System_linkPrintStatistics(pObj->UltrasonicCaptureLinkID);
       System_linkPrintStatistics(pObj->Dup_usLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP2_IPU1_0_2LinkID);
       System_linkPrintStatistics(pObj->Alg_UltrasonicFusionLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_IPU1_0_3LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_DSP2_2LinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->NullLinkID);
       Task_sleep(500);
}

