
SRCDIR += $(vision_sdk_PATH)/examples/tda2xx/src/draw2d

SRCS_ipu1_0 += front_view_nor.c \
		front_view_sel.c \
		full_view_front.c \
		full_view_none.c \
		full_view_rear.c \
		left_view_nor.c \
		left_view_sel.c \
		rear_view_nor.c \
		rear_view_sel.c \
		right_view_nor.c \
		right_view_sel.c \
		setting_nor.c \
		setting_sel.c \
		fullviewTxt.c \
		topviewTxt.c \
		carmask.c \
		draw2d_font_bmp.c \
        draw2d_font00.c \
        draw2d_font01.c \
        draw2d_font02.c \
        draw2d_font03.c \
        draw2d_font04.c \
        draw2d_font05.c \
        draw2d_font06.c \
        draw2d_font07.c
        
SRCS_COMMON += draw2d.c
