
SRCDIR += $(vision_sdk_PATH)/examples/tda2xx/src/draw2d

SRCS_ipu1_0 += front_view_nor.c \
		front_view_sel.c \
		full_view_front.c \
		full_view_none.c \
		full_view_rear.c \
		left_view_nor.c \
		left_view_sel.c \
		rear_view_nor.c \
		rear_view_sel.c \
		right_view_nor.c \
		right_view_sel.c \
		setting_nor.c \
		setting_sel.c \
		draw2d_font_bmp.c \
        draw2d_font00.c \
        draw2d_font01.c \
        draw2d_font02.c \
        draw2d_font03.c \
        draw2d_font04.c \
        draw2d_font05.c \
        draw2d_font06.c \
        draw2d_font07.c \
        draw2d_ti_logo.c \
        draw2d_ti_logo_1.c \
        lut16x16x0_25_129x129_0.c \
        lut16x16x0_25_129x129_1.c \
        draw2d_frontcam_logo.c \
        draw2d_sv_logo.c \
        draw2d_sv_logo_small.c \
        draw2d_jeep_Image_220x330.c \
        draw2d_jeep_Image_228x432.c \
        draw2d_jeep_Image_288x432.c \
        draw2d_ti_logo_small.c \
        draw2d_colorbar_20x720.c \
        draw2d_colorbar_35x450.c

SRCS_COMMON += draw2d.c
