/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_vipSingleCameraAnalytics_tda2xx_priv.h"
Void chains_vipSingleCameraAnalytics_tda2xx_SetLinkId(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE;
       pObj->Dup_captureLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->IPCOut_IPU1_0_EVE2_4LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_4);
       pObj->IPCIn_EVE2_IPU1_0_0LinkID      = EVE2_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_SparseOpticalFlowLinkID    = EVE2_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE2_A15_0_0LinkID      = EVE2_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_A15_0_EVE2_3LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_3);
       pObj->IPCOut_IPU1_0_A15_0_3LinkID    = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_3);
       pObj->IPCIn_A15_0_IPU1_0_2LinkID     = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->Merge_sofLinkID                = A15_0_LINK (SYSTEM_LINK_ID_MERGE_1);
       pObj->Sync_sofLinkID                 = A15_0_LINK (SYSTEM_LINK_ID_SYNC_1);
       pObj->Alg_SparseOpticalFlowDrawLinkID = A15_0_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->IPCOut_A15_0_IPU1_0_1LinkID    = A15_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_IPU1_0_A15_0_2LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->IPCOut_IPU1_0_DSP2_2LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_DSP2_IPU1_0_0LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_LaneDetectLinkID           = DSP2_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP2_A15_0_0LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_A15_0_DSP2_1LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->IPCOut_IPU1_0_A15_0_1LinkID    = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_A15_0_IPU1_0_0LinkID     = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Merge_ldLinkID                 = A15_0_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->Sync_ldLinkID                  = A15_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_LaneDetectDrawLinkID       = A15_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_A15_0_IPU1_0_0LinkID    = A15_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_A15_0_1LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->IPCOut_IPU1_0_EVE1_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_EVE1_IPU1_0_0LinkID      = EVE1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_FeaturePlaneComputationLinkID = EVE1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_EVE1_DSP1_0LinkID       = EVE1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP1_EVE1_0LinkID        = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_ObjectDetectionLinkID      = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP1_IPU1_0_0LinkID     = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_DSP1_0LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Merge_pd_tsrLinkID             = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->Sync_pd_tsrLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_ObjectDrawLinkID           = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->Merge_algLinkID                = IPU1_0_LINK (SYSTEM_LINK_ID_MERGE_1);
       pObj->Sync_algLinkID                 = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_1);
       pObj->Alg_DmaSwMsLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->Display_algLinkID              = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_1;
}

Void chains_vipSingleCameraAnalytics_tda2xx_ResetLinkPrms(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       DupLink_CreateParams_Init(&pObj->Dup_capturePrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE2_4Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE2_IPU1_0_0Prm);
       AlgorithmLink_SparseOpticalFlow_Init(&pObj->Alg_SparseOpticalFlowPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE2_A15_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_EVE2_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_A15_0_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_IPU1_0_2Prm);
       MergeLink_CreateParams_Init(&pObj->Merge_sofPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_sofPrm);
       AlgorithmLink_sparseOpticalFlowDraw_Init(&pObj->Alg_SparseOpticalFlowDrawPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_A15_0_IPU1_0_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_A15_0_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP2_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP2_IPU1_0_0Prm);
       AlgorithmLink_LaneDetect_Init(&pObj->Alg_LaneDetectPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_A15_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_DSP2_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_A15_0_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_IPU1_0_0Prm);
       MergeLink_CreateParams_Init(&pObj->Merge_ldPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_ldPrm);
       AlgorithmLink_LaneDetectDraw_Init(&pObj->Alg_LaneDetectDrawPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_A15_0_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_A15_0_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_EVE1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_EVE1_IPU1_0_0Prm);
       AlgorithmLink_FeatureComputation_Init(&pObj->Alg_FeaturePlaneComputationPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_EVE1_DSP1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_EVE1_0Prm);
       AlgorithmLink_ObjectDetection_Init(&pObj->Alg_ObjectDetectionPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_DSP1_0Prm);
       MergeLink_CreateParams_Init(&pObj->Merge_pd_tsrPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_pd_tsrPrm);
       AlgorithmLink_ObjectDraw_Init(&pObj->Alg_ObjectDrawPrm);
       MergeLink_CreateParams_Init(&pObj->Merge_algPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_algPrm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMsPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_algPrm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
}

Void chains_vipSingleCameraAnalytics_tda2xx_SetPrms(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){
       (pObj->Dup_capturePrm).numOutQue = 6;
       (pObj->Alg_SparseOpticalFlowPrm).baseClassCreate.size  = sizeof(AlgorithmLink_SparseOpticalFlowCreateParams);
       (pObj->Alg_SparseOpticalFlowPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_SPARSE_OPTICAL_FLOW;
       (pObj->Merge_sofPrm).numInQue = 2;
       (pObj->Alg_SparseOpticalFlowDrawPrm).baseClassCreate.size  = sizeof(AlgorithmLink_sparseOpticalFlowDrawCreateParams);
       (pObj->Alg_SparseOpticalFlowDrawPrm).baseClassCreate.algId  = ALGORITHM_LINK_A15_ALG_SOF_DRAW;
       (pObj->Alg_LaneDetectPrm).baseClassCreate.size  = sizeof(AlgorithmLink_LaneDetectCreateParams);
       (pObj->Alg_LaneDetectPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_LANE_DETECT;
       (pObj->Merge_ldPrm).numInQue = 2;
       (pObj->Alg_LaneDetectDrawPrm).baseClassCreate.size  = sizeof(AlgorithmLink_LaneDetectDrawCreateParams);
       (pObj->Alg_LaneDetectDrawPrm).baseClassCreate.algId  = ALGORITHM_LINK_A15_ALG_LANE_DETECT_DRAW;
       (pObj->Alg_FeaturePlaneComputationPrm).baseClassCreate.size  = sizeof(AlgorithmLink_FeaturePlaneComputationCreateParams);
       (pObj->Alg_FeaturePlaneComputationPrm).baseClassCreate.algId  = ALGORITHM_LINK_EVE_ALG_FEATUREPLANECOMPUTE;
       (pObj->Alg_ObjectDetectionPrm).baseClassCreate.size  = sizeof(AlgorithmLink_ObjectDetectionCreateParams);
       (pObj->Alg_ObjectDetectionPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_OBJECTDETECTION;
       (pObj->Merge_pd_tsrPrm).numInQue = 2;
       (pObj->Alg_ObjectDrawPrm).baseClassCreate.size  = sizeof(AlgorithmLink_ObjectDrawCreateParams);
       (pObj->Alg_ObjectDrawPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_PD_DRAW;
       (pObj->Merge_algPrm).numInQue = 3;
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
}

Void chains_vipSingleCameraAnalytics_tda2xx_ConnectLinks(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){

       //Capture -> Dup_capture
       pObj->CapturePrm.outQueParams.nextLink = pObj->Dup_captureLinkID;
       pObj->Dup_capturePrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->Dup_capturePrm.inQueParams.prevLinkQueId = 0;

       //Dup_capture -> Merge_pd_tsr
       pObj->Dup_capturePrm.outQueParams[0].nextLink = pObj->Merge_pd_tsrLinkID;
       pObj->Merge_pd_tsrPrm.inQueParams[0].prevLinkId = pObj->Dup_captureLinkID;
       pObj->Merge_pd_tsrPrm.inQueParams[0].prevLinkQueId = 0;

       //Dup_capture -> IPCOut_IPU1_0_EVE1_0
       pObj->Dup_capturePrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_EVE1_0Prm.inQueParams.prevLinkQueId = 1;

       //Dup_capture -> IPCOut_IPU1_0_A15_0_1
       pObj->Dup_capturePrm.outQueParams[2].nextLink = pObj->IPCOut_IPU1_0_A15_0_1LinkID;
       pObj->IPCOut_IPU1_0_A15_0_1Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_A15_0_1Prm.inQueParams.prevLinkQueId = 2;

       //Dup_capture -> IPCOut_IPU1_0_DSP2_2
       pObj->Dup_capturePrm.outQueParams[3].nextLink = pObj->IPCOut_IPU1_0_DSP2_2LinkID;
       pObj->IPCOut_IPU1_0_DSP2_2Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_DSP2_2Prm.inQueParams.prevLinkQueId = 3;

       //Dup_capture -> IPCOut_IPU1_0_A15_0_3
       pObj->Dup_capturePrm.outQueParams[4].nextLink = pObj->IPCOut_IPU1_0_A15_0_3LinkID;
       pObj->IPCOut_IPU1_0_A15_0_3Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_A15_0_3Prm.inQueParams.prevLinkQueId = 4;

       //Dup_capture -> IPCOut_IPU1_0_EVE2_4
       pObj->Dup_capturePrm.outQueParams[5].nextLink = pObj->IPCOut_IPU1_0_EVE2_4LinkID;
       pObj->IPCOut_IPU1_0_EVE2_4Prm.inQueParams.prevLinkId = pObj->Dup_captureLinkID;
       pObj->IPCOut_IPU1_0_EVE2_4Prm.inQueParams.prevLinkQueId = 5;

       //IPCOut_IPU1_0_EVE2_4 -> IPCIn_EVE2_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE2_4Prm.outQueParams.nextLink = pObj->IPCIn_EVE2_IPU1_0_0LinkID;
       pObj->IPCIn_EVE2_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE2_4LinkID;
       pObj->IPCIn_EVE2_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE2_IPU1_0_0 -> Alg_SparseOpticalFlow
       pObj->IPCIn_EVE2_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_SparseOpticalFlowLinkID;
       pObj->Alg_SparseOpticalFlowPrm.inQueParams.prevLinkId = pObj->IPCIn_EVE2_IPU1_0_0LinkID;
       pObj->Alg_SparseOpticalFlowPrm.inQueParams.prevLinkQueId = 0;

       //Alg_SparseOpticalFlow -> IPCOut_EVE2_A15_0_0
       pObj->Alg_SparseOpticalFlowPrm.outQueParams.nextLink = pObj->IPCOut_EVE2_A15_0_0LinkID;
       pObj->IPCOut_EVE2_A15_0_0Prm.inQueParams.prevLinkId = pObj->Alg_SparseOpticalFlowLinkID;
       pObj->IPCOut_EVE2_A15_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE2_A15_0_0 -> IPCIn_A15_0_EVE2_3
       pObj->IPCOut_EVE2_A15_0_0Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_EVE2_3LinkID;
       pObj->IPCIn_A15_0_EVE2_3Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE2_A15_0_0LinkID;
       pObj->IPCIn_A15_0_EVE2_3Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_EVE2_3 -> Merge_sof
       pObj->IPCIn_A15_0_EVE2_3Prm.outQueParams.nextLink = pObj->Merge_sofLinkID;
       pObj->Merge_sofPrm.inQueParams[1].prevLinkId = pObj->IPCIn_A15_0_EVE2_3LinkID;
       pObj->Merge_sofPrm.inQueParams[1].prevLinkQueId = 0;

       //IPCOut_IPU1_0_A15_0_3 -> IPCIn_A15_0_IPU1_0_2
       pObj->IPCOut_IPU1_0_A15_0_3Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_IPU1_0_2LinkID;
       pObj->IPCIn_A15_0_IPU1_0_2Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_A15_0_3LinkID;
       pObj->IPCIn_A15_0_IPU1_0_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_IPU1_0_2 -> Merge_sof
       pObj->IPCIn_A15_0_IPU1_0_2Prm.outQueParams.nextLink = pObj->Merge_sofLinkID;
       pObj->Merge_sofPrm.inQueParams[0].prevLinkId = pObj->IPCIn_A15_0_IPU1_0_2LinkID;
       pObj->Merge_sofPrm.inQueParams[0].prevLinkQueId = 0;

       //Merge_sof -> Sync_sof
       pObj->Merge_sofPrm.outQueParams.nextLink = pObj->Sync_sofLinkID;
       pObj->Sync_sofPrm.inQueParams.prevLinkId = pObj->Merge_sofLinkID;
       pObj->Sync_sofPrm.inQueParams.prevLinkQueId = 0;

       //Sync_sof -> Alg_SparseOpticalFlowDraw
       pObj->Sync_sofPrm.outQueParams.nextLink = pObj->Alg_SparseOpticalFlowDrawLinkID;
       pObj->Alg_SparseOpticalFlowDrawPrm.inQueParams.prevLinkId = pObj->Sync_sofLinkID;
       pObj->Alg_SparseOpticalFlowDrawPrm.inQueParams.prevLinkQueId = 0;

       //Alg_SparseOpticalFlowDraw -> IPCOut_A15_0_IPU1_0_1
       pObj->Alg_SparseOpticalFlowDrawPrm.outQueParams.nextLink = pObj->IPCOut_A15_0_IPU1_0_1LinkID;
       pObj->IPCOut_A15_0_IPU1_0_1Prm.inQueParams.prevLinkId = pObj->Alg_SparseOpticalFlowDrawLinkID;
       pObj->IPCOut_A15_0_IPU1_0_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_A15_0_IPU1_0_1 -> IPCIn_IPU1_0_A15_0_2
       pObj->IPCOut_A15_0_IPU1_0_1Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_A15_0_2LinkID;
       pObj->IPCIn_IPU1_0_A15_0_2Prm.inQueParams.prevLinkId = pObj->IPCOut_A15_0_IPU1_0_1LinkID;
       pObj->IPCIn_IPU1_0_A15_0_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_A15_0_2 -> Merge_alg
       pObj->IPCIn_IPU1_0_A15_0_2Prm.outQueParams.nextLink = pObj->Merge_algLinkID;
       pObj->Merge_algPrm.inQueParams[2].prevLinkId = pObj->IPCIn_IPU1_0_A15_0_2LinkID;
       pObj->Merge_algPrm.inQueParams[2].prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP2_2 -> IPCIn_DSP2_IPU1_0_0
       pObj->IPCOut_IPU1_0_DSP2_2Prm.outQueParams.nextLink = pObj->IPCIn_DSP2_IPU1_0_0LinkID;
       pObj->IPCIn_DSP2_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP2_2LinkID;
       pObj->IPCIn_DSP2_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP2_IPU1_0_0 -> Alg_LaneDetect
       pObj->IPCIn_DSP2_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_LaneDetectLinkID;
       pObj->Alg_LaneDetectPrm.inQueParams.prevLinkId = pObj->IPCIn_DSP2_IPU1_0_0LinkID;
       pObj->Alg_LaneDetectPrm.inQueParams.prevLinkQueId = 0;

       //Alg_LaneDetect -> IPCOut_DSP2_A15_0_0
       pObj->Alg_LaneDetectPrm.outQueParams.nextLink = pObj->IPCOut_DSP2_A15_0_0LinkID;
       pObj->IPCOut_DSP2_A15_0_0Prm.inQueParams.prevLinkId = pObj->Alg_LaneDetectLinkID;
       pObj->IPCOut_DSP2_A15_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP2_A15_0_0 -> IPCIn_A15_0_DSP2_1
       pObj->IPCOut_DSP2_A15_0_0Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_DSP2_1LinkID;
       pObj->IPCIn_A15_0_DSP2_1Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_A15_0_0LinkID;
       pObj->IPCIn_A15_0_DSP2_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_DSP2_1 -> Merge_ld
       pObj->IPCIn_A15_0_DSP2_1Prm.outQueParams.nextLink = pObj->Merge_ldLinkID;
       pObj->Merge_ldPrm.inQueParams[1].prevLinkId = pObj->IPCIn_A15_0_DSP2_1LinkID;
       pObj->Merge_ldPrm.inQueParams[1].prevLinkQueId = 0;

       //IPCOut_IPU1_0_A15_0_1 -> IPCIn_A15_0_IPU1_0_0
       pObj->IPCOut_IPU1_0_A15_0_1Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_A15_0_1LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_IPU1_0_0 -> Merge_ld
       pObj->IPCIn_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->Merge_ldLinkID;
       pObj->Merge_ldPrm.inQueParams[0].prevLinkId = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->Merge_ldPrm.inQueParams[0].prevLinkQueId = 0;

       //Merge_ld -> Sync_ld
       pObj->Merge_ldPrm.outQueParams.nextLink = pObj->Sync_ldLinkID;
       pObj->Sync_ldPrm.inQueParams.prevLinkId = pObj->Merge_ldLinkID;
       pObj->Sync_ldPrm.inQueParams.prevLinkQueId = 0;

       //Sync_ld -> Alg_LaneDetectDraw
       pObj->Sync_ldPrm.outQueParams.nextLink = pObj->Alg_LaneDetectDrawLinkID;
       pObj->Alg_LaneDetectDrawPrm.inQueParams.prevLinkId = pObj->Sync_ldLinkID;
       pObj->Alg_LaneDetectDrawPrm.inQueParams.prevLinkQueId = 0;

       //Alg_LaneDetectDraw -> IPCOut_A15_0_IPU1_0_0
       pObj->Alg_LaneDetectDrawPrm.outQueParams.nextLink = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_LaneDetectDrawLinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_A15_0_IPU1_0_0 -> IPCIn_IPU1_0_A15_0_1
       pObj->IPCOut_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_A15_0_1LinkID;
       pObj->IPCIn_IPU1_0_A15_0_1Prm.inQueParams.prevLinkId = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_A15_0_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_A15_0_1 -> Merge_alg
       pObj->IPCIn_IPU1_0_A15_0_1Prm.outQueParams.nextLink = pObj->Merge_algLinkID;
       pObj->Merge_algPrm.inQueParams[1].prevLinkId = pObj->IPCIn_IPU1_0_A15_0_1LinkID;
       pObj->Merge_algPrm.inQueParams[1].prevLinkQueId = 0;

       //IPCOut_IPU1_0_EVE1_0 -> IPCIn_EVE1_IPU1_0_0
       pObj->IPCOut_IPU1_0_EVE1_0Prm.outQueParams.nextLink = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_EVE1_0LinkID;
       pObj->IPCIn_EVE1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_EVE1_IPU1_0_0 -> Alg_FeaturePlaneComputation
       pObj->IPCIn_EVE1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_FeaturePlaneComputationLinkID;
       pObj->Alg_FeaturePlaneComputationPrm.inQueParams.prevLinkId = pObj->IPCIn_EVE1_IPU1_0_0LinkID;
       pObj->Alg_FeaturePlaneComputationPrm.inQueParams.prevLinkQueId = 0;

       //Alg_FeaturePlaneComputation -> IPCOut_EVE1_DSP1_0
       pObj->Alg_FeaturePlaneComputationPrm.outQueParams.nextLink = pObj->IPCOut_EVE1_DSP1_0LinkID;
       pObj->IPCOut_EVE1_DSP1_0Prm.inQueParams.prevLinkId = pObj->Alg_FeaturePlaneComputationLinkID;
       pObj->IPCOut_EVE1_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_EVE1_DSP1_0 -> IPCIn_DSP1_EVE1_0
       pObj->IPCOut_EVE1_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_EVE1_0LinkID;
       pObj->IPCIn_DSP1_EVE1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_EVE1_DSP1_0LinkID;
       pObj->IPCIn_DSP1_EVE1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_EVE1_0 -> Alg_ObjectDetection
       pObj->IPCIn_DSP1_EVE1_0Prm.outQueParams.nextLink = pObj->Alg_ObjectDetectionLinkID;
       pObj->Alg_ObjectDetectionPrm.inQueParams.prevLinkId = pObj->IPCIn_DSP1_EVE1_0LinkID;
       pObj->Alg_ObjectDetectionPrm.inQueParams.prevLinkQueId = 0;

       //Alg_ObjectDetection -> IPCOut_DSP1_IPU1_0_0
       pObj->Alg_ObjectDetectionPrm.outQueParams.nextLink = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Alg_ObjectDetectionLinkID;
       pObj->IPCOut_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP1_IPU1_0_0 -> IPCIn_IPU1_0_DSP1_0
       pObj->IPCOut_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_DSP1_0 -> Merge_pd_tsr
       pObj->IPCIn_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->Merge_pd_tsrLinkID;
       pObj->Merge_pd_tsrPrm.inQueParams[1].prevLinkId = pObj->IPCIn_IPU1_0_DSP1_0LinkID;
       pObj->Merge_pd_tsrPrm.inQueParams[1].prevLinkQueId = 0;

       //Merge_pd_tsr -> Sync_pd_tsr
       pObj->Merge_pd_tsrPrm.outQueParams.nextLink = pObj->Sync_pd_tsrLinkID;
       pObj->Sync_pd_tsrPrm.inQueParams.prevLinkId = pObj->Merge_pd_tsrLinkID;
       pObj->Sync_pd_tsrPrm.inQueParams.prevLinkQueId = 0;

       //Sync_pd_tsr -> Alg_ObjectDraw
       pObj->Sync_pd_tsrPrm.outQueParams.nextLink = pObj->Alg_ObjectDrawLinkID;
       pObj->Alg_ObjectDrawPrm.inQueParams.prevLinkId = pObj->Sync_pd_tsrLinkID;
       pObj->Alg_ObjectDrawPrm.inQueParams.prevLinkQueId = 0;

       //Alg_ObjectDraw -> Merge_alg
       pObj->Alg_ObjectDrawPrm.outQueParams.nextLink = pObj->Merge_algLinkID;
       pObj->Merge_algPrm.inQueParams[0].prevLinkId = pObj->Alg_ObjectDrawLinkID;
       pObj->Merge_algPrm.inQueParams[0].prevLinkQueId = 0;

       //Merge_alg -> Sync_alg
       pObj->Merge_algPrm.outQueParams.nextLink = pObj->Sync_algLinkID;
       pObj->Sync_algPrm.inQueParams.prevLinkId = pObj->Merge_algLinkID;
       pObj->Sync_algPrm.inQueParams.prevLinkQueId = 0;

       //Sync_alg -> Alg_DmaSwMs
       pObj->Sync_algPrm.outQueParams.nextLink = pObj->Alg_DmaSwMsLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkId = pObj->Sync_algLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs -> Display_alg
       pObj->Alg_DmaSwMsPrm.outQueParams.nextLink = pObj->Display_algLinkID;
       pObj->Display_algPrm.inQueParams.prevLinkId = pObj->Alg_DmaSwMsLinkID;
       pObj->Display_algPrm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_vipSingleCameraAnalytics_tda2xx_Create(chains_vipSingleCameraAnalytics_tda2xxObj *pObj, Void *appObj){

       Int32 status;

       chains_vipSingleCameraAnalytics_tda2xx_SetLinkId(pObj);
       chains_vipSingleCameraAnalytics_tda2xx_ResetLinkPrms(pObj);

       chains_vipSingleCameraAnalytics_tda2xx_SetPrms(pObj);
       chains_vipSingleCameraAnalytics_tda2xx_SetAppPrms(pObj, appObj);

       chains_vipSingleCameraAnalytics_tda2xx_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_captureLinkID, &pObj->Dup_capturePrm, sizeof(pObj->Dup_capturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE2_4LinkID, &pObj->IPCOut_IPU1_0_EVE2_4Prm, sizeof(pObj->IPCOut_IPU1_0_EVE2_4Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE2_IPU1_0_0LinkID, &pObj->IPCIn_EVE2_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE2_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_SparseOpticalFlowLinkID, &pObj->Alg_SparseOpticalFlowPrm, sizeof(pObj->Alg_SparseOpticalFlowPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE2_A15_0_0LinkID, &pObj->IPCOut_EVE2_A15_0_0Prm, sizeof(pObj->IPCOut_EVE2_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_EVE2_3LinkID, &pObj->IPCIn_A15_0_EVE2_3Prm, sizeof(pObj->IPCIn_A15_0_EVE2_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_A15_0_3LinkID, &pObj->IPCOut_IPU1_0_A15_0_3Prm, sizeof(pObj->IPCOut_IPU1_0_A15_0_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_IPU1_0_2LinkID, &pObj->IPCIn_A15_0_IPU1_0_2Prm, sizeof(pObj->IPCIn_A15_0_IPU1_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_sofLinkID, &pObj->Merge_sofPrm, sizeof(pObj->Merge_sofPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_sofLinkID, &pObj->Sync_sofPrm, sizeof(pObj->Sync_sofPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_SparseOpticalFlowDrawLinkID, &pObj->Alg_SparseOpticalFlowDrawPrm, sizeof(pObj->Alg_SparseOpticalFlowDrawPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_A15_0_IPU1_0_1LinkID, &pObj->IPCOut_A15_0_IPU1_0_1Prm, sizeof(pObj->IPCOut_A15_0_IPU1_0_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_A15_0_2LinkID, &pObj->IPCIn_IPU1_0_A15_0_2Prm, sizeof(pObj->IPCIn_IPU1_0_A15_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP2_2LinkID, &pObj->IPCOut_IPU1_0_DSP2_2Prm, sizeof(pObj->IPCOut_IPU1_0_DSP2_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP2_IPU1_0_0LinkID, &pObj->IPCIn_DSP2_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP2_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_LaneDetectLinkID, &pObj->Alg_LaneDetectPrm, sizeof(pObj->Alg_LaneDetectPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_A15_0_0LinkID, &pObj->IPCOut_DSP2_A15_0_0Prm, sizeof(pObj->IPCOut_DSP2_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_DSP2_1LinkID, &pObj->IPCIn_A15_0_DSP2_1Prm, sizeof(pObj->IPCIn_A15_0_DSP2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_A15_0_1LinkID, &pObj->IPCOut_IPU1_0_A15_0_1Prm, sizeof(pObj->IPCOut_IPU1_0_A15_0_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_IPU1_0_0LinkID, &pObj->IPCIn_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCIn_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_ldLinkID, &pObj->Merge_ldPrm, sizeof(pObj->Merge_ldPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_ldLinkID, &pObj->Sync_ldPrm, sizeof(pObj->Sync_ldPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_LaneDetectDrawLinkID, &pObj->Alg_LaneDetectDrawPrm, sizeof(pObj->Alg_LaneDetectDrawPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_A15_0_IPU1_0_0LinkID, &pObj->IPCOut_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCOut_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_A15_0_1LinkID, &pObj->IPCIn_IPU1_0_A15_0_1Prm, sizeof(pObj->IPCIn_IPU1_0_A15_0_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_EVE1_0LinkID, &pObj->IPCOut_IPU1_0_EVE1_0Prm, sizeof(pObj->IPCOut_IPU1_0_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_EVE1_IPU1_0_0LinkID, &pObj->IPCIn_EVE1_IPU1_0_0Prm, sizeof(pObj->IPCIn_EVE1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_FeaturePlaneComputationLinkID, &pObj->Alg_FeaturePlaneComputationPrm, sizeof(pObj->Alg_FeaturePlaneComputationPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_EVE1_DSP1_0LinkID, &pObj->IPCOut_EVE1_DSP1_0Prm, sizeof(pObj->IPCOut_EVE1_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_EVE1_0LinkID, &pObj->IPCIn_DSP1_EVE1_0Prm, sizeof(pObj->IPCIn_DSP1_EVE1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_ObjectDetectionLinkID, &pObj->Alg_ObjectDetectionPrm, sizeof(pObj->Alg_ObjectDetectionPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_IPU1_0_0LinkID, &pObj->IPCOut_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCOut_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_DSP1_0LinkID, &pObj->IPCIn_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCIn_IPU1_0_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_pd_tsrLinkID, &pObj->Merge_pd_tsrPrm, sizeof(pObj->Merge_pd_tsrPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_pd_tsrLinkID, &pObj->Sync_pd_tsrPrm, sizeof(pObj->Sync_pd_tsrPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_ObjectDrawLinkID, &pObj->Alg_ObjectDrawPrm, sizeof(pObj->Alg_ObjectDrawPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Merge_algLinkID, &pObj->Merge_algPrm, sizeof(pObj->Merge_algPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_algLinkID, &pObj->Sync_algPrm, sizeof(pObj->Sync_algPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMsLinkID, &pObj->Alg_DmaSwMsPrm, sizeof(pObj->Alg_DmaSwMsPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_algLinkID, &pObj->Display_algPrm, sizeof(pObj->Display_algPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCameraAnalytics_tda2xx_Start(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_ObjectDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_pd_tsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_pd_tsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_ObjectDetectionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE1_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_FeaturePlaneComputationLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_LaneDetectDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_ldLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_ldLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_LaneDetectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_A15_0_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_SparseOpticalFlowDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_sofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Merge_sofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_A15_0_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_EVE2_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_EVE2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_SparseOpticalFlowLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_EVE2_4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCameraAnalytics_tda2xx_Stop(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_ObjectDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_pd_tsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_pd_tsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_ObjectDetectionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE1_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_FeaturePlaneComputationLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_LaneDetectDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_ldLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_ldLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_LaneDetectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_A15_0_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_SparseOpticalFlowDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_sofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Merge_sofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_A15_0_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_EVE2_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_EVE2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_SparseOpticalFlowLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_EVE2_4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_vipSingleCameraAnalytics_tda2xx_Delete(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_algLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_ObjectDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_pd_tsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_pd_tsrLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_ObjectDetectionLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE1_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_FeaturePlaneComputationLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_LaneDetectDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_ldLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_ldLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_LaneDetectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_A15_0_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_SparseOpticalFlowDrawLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_sofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Merge_sofLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_IPU1_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_A15_0_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_EVE2_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_EVE2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_SparseOpticalFlowLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_EVE2_4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_captureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_vipSingleCameraAnalytics_tda2xx_printBufferStatistics(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_captureLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE2_4LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_SparseOpticalFlowLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE2_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_EVE2_3LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_A15_0_3LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_IPU1_0_2LinkID);
       System_linkPrintBufferStatistics(pObj->Merge_sofLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_sofLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_SparseOpticalFlowDrawLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_A15_0_IPU1_0_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_A15_0_2LinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_LaneDetectLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_A15_0_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Merge_ldLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_ldLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_LaneDetectDrawLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_A15_0_1LinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_FeaturePlaneComputationLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_EVE1_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_EVE1_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_ObjectDetectionLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       System_linkPrintBufferStatistics(pObj->Merge_pd_tsrLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_pd_tsrLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_ObjectDrawLinkID);
       System_linkPrintBufferStatistics(pObj->Merge_algLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_algLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintBufferStatistics(pObj->Display_algLinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_vipSingleCameraAnalytics_tda2xx_printStatistics(chains_vipSingleCameraAnalytics_tda2xxObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->Dup_captureLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE2_4LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE2_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_SparseOpticalFlowLinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE2_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_EVE2_3LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_A15_0_3LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_IPU1_0_2LinkID);
       System_linkPrintStatistics(pObj->Merge_sofLinkID);
       System_linkPrintStatistics(pObj->Sync_sofLinkID);
       System_linkPrintStatistics(pObj->Alg_SparseOpticalFlowDrawLinkID);
       System_linkPrintStatistics(pObj->IPCOut_A15_0_IPU1_0_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_A15_0_2LinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP2_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_LaneDetectLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_A15_0_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Merge_ldLinkID);
       System_linkPrintStatistics(pObj->Sync_ldLinkID);
       System_linkPrintStatistics(pObj->Alg_LaneDetectDrawLinkID);
       System_linkPrintStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_A15_0_1LinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_EVE1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_EVE1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_FeaturePlaneComputationLinkID);
       System_linkPrintStatistics(pObj->IPCOut_EVE1_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_EVE1_0LinkID);
       System_linkPrintStatistics(pObj->Alg_ObjectDetectionLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_DSP1_0LinkID);
       System_linkPrintStatistics(pObj->Merge_pd_tsrLinkID);
       System_linkPrintStatistics(pObj->Sync_pd_tsrLinkID);
       System_linkPrintStatistics(pObj->Alg_ObjectDrawLinkID);
       System_linkPrintStatistics(pObj->Merge_algLinkID);
       System_linkPrintStatistics(pObj->Sync_algLinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintStatistics(pObj->Display_algLinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

