/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_lvdsVipMultiCam_Display_tda3xx_priv.h"
Void chains_lvdsVipMultiCam_Display_tda3xx_SetLinkId(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE;
       pObj->SelectLinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_SELECT_0);
       pObj->Sync_2LinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_1);
       pObj->Alg_DmaSwMs_2LinkID            = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->Display_video2LinkID           = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->Sync_1LinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_DmaSwMs_1LinkID            = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->Display_video1LinkID           = SYSTEM_LINK_ID_DISPLAY_1;
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_2;
}

Void chains_lvdsVipMultiCam_Display_tda3xx_ResetLinkPrms(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       SelectLink_CreateParams_Init(&pObj->SelectPrm);
       SyncLink_CreateParams_Init(&pObj->Sync_2Prm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMs_2Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_video2Prm);
       SyncLink_CreateParams_Init(&pObj->Sync_1Prm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMs_1Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_video1Prm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
}

Void chains_lvdsVipMultiCam_Display_tda3xx_SetPrms(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){
       (pObj->SelectPrm).numOutQue = 2;
       (pObj->Alg_DmaSwMs_2Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMs_2Prm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
       (pObj->Alg_DmaSwMs_1Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMs_1Prm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
}

Void chains_lvdsVipMultiCam_Display_tda3xx_ConnectLinks(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){

       //Capture -> Select
       pObj->CapturePrm.outQueParams.nextLink = pObj->SelectLinkID;
       pObj->SelectPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->SelectPrm.inQueParams.prevLinkQueId = 0;

       //Select -> Sync_1
       pObj->SelectPrm.outQueParams[0].nextLink = pObj->Sync_1LinkID;
       pObj->Sync_1Prm.inQueParams.prevLinkId = pObj->SelectLinkID;
       pObj->Sync_1Prm.inQueParams.prevLinkQueId = 0;

       //Select -> Sync_2
       pObj->SelectPrm.outQueParams[1].nextLink = pObj->Sync_2LinkID;
       pObj->Sync_2Prm.inQueParams.prevLinkId = pObj->SelectLinkID;
       pObj->Sync_2Prm.inQueParams.prevLinkQueId = 1;

       //Sync_2 -> Alg_DmaSwMs_2
       pObj->Sync_2Prm.outQueParams.nextLink = pObj->Alg_DmaSwMs_2LinkID;
       pObj->Alg_DmaSwMs_2Prm.inQueParams.prevLinkId = pObj->Sync_2LinkID;
       pObj->Alg_DmaSwMs_2Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs_2 -> Display_video2
       pObj->Alg_DmaSwMs_2Prm.outQueParams.nextLink = pObj->Display_video2LinkID;
       pObj->Display_video2Prm.inQueParams.prevLinkId = pObj->Alg_DmaSwMs_2LinkID;
       pObj->Display_video2Prm.inQueParams.prevLinkQueId = 0;

       //Sync_1 -> Alg_DmaSwMs_1
       pObj->Sync_1Prm.outQueParams.nextLink = pObj->Alg_DmaSwMs_1LinkID;
       pObj->Alg_DmaSwMs_1Prm.inQueParams.prevLinkId = pObj->Sync_1LinkID;
       pObj->Alg_DmaSwMs_1Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs_1 -> Display_video1
       pObj->Alg_DmaSwMs_1Prm.outQueParams.nextLink = pObj->Display_video1LinkID;
       pObj->Display_video1Prm.inQueParams.prevLinkId = pObj->Alg_DmaSwMs_1LinkID;
       pObj->Display_video1Prm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_lvdsVipMultiCam_Display_tda3xx_Create(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj, Void *appObj){

       Int32 status;

       chains_lvdsVipMultiCam_Display_tda3xx_SetLinkId(pObj);
       chains_lvdsVipMultiCam_Display_tda3xx_ResetLinkPrms(pObj);

       chains_lvdsVipMultiCam_Display_tda3xx_SetPrms(pObj);
       chains_lvdsVipMultiCam_Display_tda3xx_SetAppPrms(pObj, appObj);

       chains_lvdsVipMultiCam_Display_tda3xx_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SelectLinkID, &pObj->SelectPrm, sizeof(pObj->SelectPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_2LinkID, &pObj->Sync_2Prm, sizeof(pObj->Sync_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMs_2LinkID, &pObj->Alg_DmaSwMs_2Prm, sizeof(pObj->Alg_DmaSwMs_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_video2LinkID, &pObj->Display_video2Prm, sizeof(pObj->Display_video2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_1LinkID, &pObj->Sync_1Prm, sizeof(pObj->Sync_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMs_1LinkID, &pObj->Alg_DmaSwMs_1Prm, sizeof(pObj->Alg_DmaSwMs_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_video1LinkID, &pObj->Display_video1Prm, sizeof(pObj->Display_video1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda3xx_Start(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_video1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMs_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_video2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMs_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda3xx_Stop(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_video1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMs_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_video2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMs_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda3xx_Delete(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_video1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMs_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_video2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMs_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_lvdsVipMultiCam_Display_tda3xx_printBufferStatistics(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->SelectLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_2LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMs_2LinkID);
       System_linkPrintBufferStatistics(pObj->Display_video2LinkID);
       System_linkPrintBufferStatistics(pObj->Sync_1LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMs_1LinkID);
       System_linkPrintBufferStatistics(pObj->Display_video1LinkID);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_lvdsVipMultiCam_Display_tda3xx_printStatistics(chains_lvdsVipMultiCam_Display_tda3xxObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->SelectLinkID);
       System_linkPrintStatistics(pObj->Sync_2LinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMs_2LinkID);
       System_linkPrintStatistics(pObj->Display_video2LinkID);
       System_linkPrintStatistics(pObj->Sync_1LinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMs_1LinkID);
       System_linkPrintStatistics(pObj->Display_video1LinkID);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

