/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCam_EncDec_Display_H_
#define _chains_vipSingleCam_EncDec_Display_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/encLink.h>
#include <include/link_api/decLink.h>
#include <include/link_api/vpeLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    EncodeLinkID;
       UInt32    DecodeLinkID;
       UInt32    VPELinkID;
       UInt32    Display_VideoLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       EncLink_CreateParams                    EncodePrm;
       DecLink_CreateParams                    DecodePrm;
       VpeLink_CreateParams                    VPEPrm;
       DisplayLink_CreateParams                Display_VideoPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCam_EncDec_DisplayObj;

Void chains_vipSingleCam_EncDec_Display_SetLinkId(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Void chains_vipSingleCam_EncDec_Display_ResetLinkPrms(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Void chains_vipSingleCam_EncDec_Display_SetPrms(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Void chains_vipSingleCam_EncDec_Display_ConnectLinks(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Int32 chains_vipSingleCam_EncDec_Display_Create(chains_vipSingleCam_EncDec_DisplayObj *pObj, Void *appObj);

Int32 chains_vipSingleCam_EncDec_Display_Start(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Int32 chains_vipSingleCam_EncDec_Display_Stop(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Int32 chains_vipSingleCam_EncDec_Display_Delete(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Void chains_vipSingleCam_EncDec_Display_printBufferStatistics(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Void chains_vipSingleCam_EncDec_Display_printStatistics(chains_vipSingleCam_EncDec_DisplayObj *pObj);

Void chains_vipSingleCam_EncDec_Display_SetAppPrms(chains_vipSingleCam_EncDec_DisplayObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCam_EncDec_Display_H_ */
