/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_avbRxDecodeDisplay_priv.h"
Void chains_avbRxDecodeDisplay_SetLinkId(chains_avbRxDecodeDisplayObj *pObj){
       pObj->AvbRxLinkID                    = IPU1_0_LINK (SYSTEM_LINK_ID_AVB_RX);
       pObj->DecodeLinkID                   = SYSTEM_LINK_ID_VDEC_0;
       pObj->Sync_svLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->IPCOut_IPU1_0_A15_0_0LinkID    = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_A15_0_IPU1_0_0LinkID     = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->SgxDisplayLinkID               = SYSTEM_LINK_ID_SGXDISPLAY_0;
}

Void chains_avbRxDecodeDisplay_ResetLinkPrms(chains_avbRxDecodeDisplayObj *pObj){
       AvbRxLink_CreateParams_Init(&pObj->AvbRxPrm);
       DecLink_CreateParams_Init(&pObj->DecodePrm);
       SyncLink_CreateParams_Init(&pObj->Sync_svPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_A15_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_IPU1_0_0Prm);
       SgxDisplayLink_CreateParams_Init(&pObj->SgxDisplayPrm);
}

Void chains_avbRxDecodeDisplay_SetPrms(chains_avbRxDecodeDisplayObj *pObj){
}

Void chains_avbRxDecodeDisplay_ConnectLinks(chains_avbRxDecodeDisplayObj *pObj){

       //AvbRx -> Decode
       pObj->AvbRxPrm.outQueParams.nextLink = pObj->DecodeLinkID;
       pObj->DecodePrm.inQueParams.prevLinkId = pObj->AvbRxLinkID;
       pObj->DecodePrm.inQueParams.prevLinkQueId = 0;

       //Decode -> Sync_sv
       pObj->DecodePrm.outQueParams.nextLink = pObj->Sync_svLinkID;
       pObj->Sync_svPrm.inQueParams.prevLinkId = pObj->DecodeLinkID;
       pObj->Sync_svPrm.inQueParams.prevLinkQueId = 0;

       //Sync_sv -> IPCOut_IPU1_0_A15_0_0
       pObj->Sync_svPrm.outQueParams.nextLink = pObj->IPCOut_IPU1_0_A15_0_0LinkID;
       pObj->IPCOut_IPU1_0_A15_0_0Prm.inQueParams.prevLinkId = pObj->Sync_svLinkID;
       pObj->IPCOut_IPU1_0_A15_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_IPU1_0_A15_0_0 -> IPCIn_A15_0_IPU1_0_0
       pObj->IPCOut_IPU1_0_A15_0_0Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_A15_0_0LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_IPU1_0_0 -> SgxDisplay
       pObj->IPCIn_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->SgxDisplayLinkID;
       pObj->SgxDisplayPrm.inQueParams.prevLinkId = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->SgxDisplayPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_avbRxDecodeDisplay_Create(chains_avbRxDecodeDisplayObj *pObj, Void *appObj){

       Int32 status;

       chains_avbRxDecodeDisplay_SetLinkId(pObj);
       chains_avbRxDecodeDisplay_ResetLinkPrms(pObj);

       chains_avbRxDecodeDisplay_SetPrms(pObj);
       chains_avbRxDecodeDisplay_SetAppPrms(pObj, appObj);

       chains_avbRxDecodeDisplay_ConnectLinks(pObj);
       status = System_linkCreate(pObj->AvbRxLinkID, &pObj->AvbRxPrm, sizeof(pObj->AvbRxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->DecodeLinkID, &pObj->DecodePrm, sizeof(pObj->DecodePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_svLinkID, &pObj->Sync_svPrm, sizeof(pObj->Sync_svPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_A15_0_0LinkID, &pObj->IPCOut_IPU1_0_A15_0_0Prm, sizeof(pObj->IPCOut_IPU1_0_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_IPU1_0_0LinkID, &pObj->IPCIn_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCIn_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SgxDisplayLinkID, &pObj->SgxDisplayPrm, sizeof(pObj->SgxDisplayPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_avbRxDecodeDisplay_Start(chains_avbRxDecodeDisplayObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->SgxDisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->AvbRxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_avbRxDecodeDisplay_Stop(chains_avbRxDecodeDisplayObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->SgxDisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->AvbRxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_avbRxDecodeDisplay_Delete(chains_avbRxDecodeDisplayObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->SgxDisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->AvbRxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_avbRxDecodeDisplay_printBufferStatistics(chains_avbRxDecodeDisplayObj *pObj){
       System_linkPrintBufferStatistics(pObj->AvbRxLinkID);
       System_linkPrintBufferStatistics(pObj->DecodeLinkID);
       System_linkPrintBufferStatistics(pObj->Sync_svLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->SgxDisplayLinkID);
       Task_sleep(500);
}

Void chains_avbRxDecodeDisplay_printStatistics(chains_avbRxDecodeDisplayObj *pObj){
       System_linkPrintStatistics(pObj->AvbRxLinkID);
       System_linkPrintStatistics(pObj->DecodeLinkID);
       System_linkPrintStatistics(pObj->Sync_svLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->SgxDisplayLinkID);
       Task_sleep(500);
}

