
SRCDIR += $(vision_sdk_PATH)/examples/tda2xx/src/links/grpxSrc

SRCS_ipu1_0 += \
		grpxSrcLink_tsk.c \
		grpxSrcLink_cpu_load.c \
		grpxSrcLink_sved_layout.c \
		grpxSrcLink_sv_sof_layout.c \
		grpxSrcLink_OF_layout.c \
		grpxSrcLink_stereo_layout.c \
		grpxSrcLink_stereo_multiFCalg_layout.c \
		grpxSrcLink_pd_tsr_ld_layout.c \
		grpxSrcLink_pd_tsr_ld_sof_layout.c \
		grpxSrcLink_ultrasonic_draw.c \
		grpxSrcLink_pd_tsr_ld_sof_stereo_layout.c \
		grpxSrcLink_svStandalone_layout.c \
		grpxSrcLink_AVM_E500_layout.c

